// Code generated by lumex; DO NOT EDIT.
//
// Source: https://core.telegram.org/bots/api
// Bot API version: 10.3

package lumex

// =================
// === Constants ===
// =================

// Update-type names, e.g. for GetUpdatesRequest.AllowedUpdates.
const (
	UpdateTypeMessage                  = "message"
	UpdateTypeEditedMessage            = "edited_message"
	UpdateTypeChannelPost              = "channel_post"
	UpdateTypeEditedChannelPost        = "edited_channel_post"
	UpdateTypeBusinessConnection       = "business_connection"
	UpdateTypeBusinessMessage          = "business_message"
	UpdateTypeEditedBusinessMessage    = "edited_business_message"
	UpdateTypeDeletedBusinessMessages  = "deleted_business_messages"
	UpdateTypeGuestMessage             = "guest_message"
	UpdateTypeMessageReaction          = "message_reaction"
	UpdateTypeMessageReactionCount     = "message_reaction_count"
	UpdateTypeInlineQuery              = "inline_query"
	UpdateTypeChosenInlineResult       = "chosen_inline_result"
	UpdateTypeCallbackQuery            = "callback_query"
	UpdateTypeShippingQuery            = "shipping_query"
	UpdateTypePreCheckoutQuery         = "pre_checkout_query"
	UpdateTypePurchasedPaidMedia       = "purchased_paid_media"
	UpdateTypePoll                     = "poll"
	UpdateTypePollAnswer               = "poll_answer"
	UpdateTypeMyChatMember             = "my_chat_member"
	UpdateTypeChatMember               = "chat_member"
	UpdateTypeChatJoinRequest          = "chat_join_request"
	UpdateTypeChatBoost                = "chat_boost"
	UpdateTypeRemovedChatBoost         = "removed_chat_boost"
	UpdateTypeManagedBot               = "managed_bot"
	UpdateTypeSubscription             = "subscription"
	UpdateTypeStoppedMessageGeneration = "stopped_message_generation"
)

// Chat actions for sendChatAction.action.
const (
	ChatActionTyping          = "typing"
	ChatActionUploadPhoto     = "upload_photo"
	ChatActionRecordVideo     = "record_video"
	ChatActionUploadVideo     = "upload_video"
	ChatActionRecordVoice     = "record_voice"
	ChatActionUploadVoice     = "upload_voice"
	ChatActionUploadDocument  = "upload_document"
	ChatActionChooseSticker   = "choose_sticker"
	ChatActionFindLocation    = "find_location"
	ChatActionRecordVideoNote = "record_video_note"
	ChatActionUploadVideoNote = "upload_video_note"
)

// Message parse modes for the parse_mode parameter.
const (
	ParseModeMarkdown   = "Markdown"
	ParseModeMarkdownV2 = "MarkdownV2"
	ParseModeHTML       = "HTML"
)
