// Code generated by lumex; DO NOT EDIT.
//
// Source: https://core.telegram.org/bots/api
// Bot API version: 10.3

package lumex

import (
	"encoding/json"
	"io"
	"os"
)

// ==============================================
// === Helper & polymorphic convenience types ===
// ==============================================

// ReplyMarkup is one of the keyboard/markup objects accepted by the
// reply_markup parameter: InlineKeyboardMarkup, ReplyKeyboardMarkup, ReplyKeyboardRemove, ForceReply.
type ReplyMarkup interface{ isReplyMarkup() }

func (*InlineKeyboardMarkup) isReplyMarkup() {}
func (*ReplyKeyboardMarkup) isReplyMarkup()  {}
func (*ReplyKeyboardRemove) isReplyMarkup()  {}
func (*ForceReply) isReplyMarkup()           {}

// InputFile represents a file to send: either a reference to an existing file
// (a file_id or an HTTP URL) or a local file to be uploaded via multipart.
type InputFile struct {
	// FileID references a file already stored on Telegram's servers.
	FileID string
	// URL is an HTTP URL for Telegram to fetch the file from.
	URL string
	// Name is the filename shown to users for an uploaded file (optional).
	Name string
	// Reader provides the file contents for an upload.
	Reader io.Reader
	// attachID is the multipart part name assigned by the client at send time.
	attachID string
}

// InputFileID references an already-uploaded file by its identifier.
func InputFileID(id string) *InputFile { return &InputFile{FileID: id} }

// InputFileURL references a remote file by URL.
func InputFileURL(url string) *InputFile { return &InputFile{URL: url} }

// InputFileReader uploads file contents read from r under the given attachment name.
func InputFileReader(name string, r io.Reader) *InputFile { return &InputFile{Name: name, Reader: r} }

// InputFilePath opens a local file for upload. The caller is responsible for the
// lifetime of the returned reader (it is *os.File).
func InputFilePath(path string) (*InputFile, error) {
	f, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	return &InputFile{Name: baseName(path), Reader: f}, nil
}

// NeedsUpload reports whether the file must be sent as a multipart attachment
// (as opposed to a file_id/URL string). A client uses Name/Reader to attach it.
func (f InputFile) NeedsUpload() bool { return f.Reader != nil }

// MarshalJSON renders the file as the string Telegram expects: a file_id, a
// URL, or an "attach://<name>" reference to a multipart part.
func (f InputFile) MarshalJSON() ([]byte, error) {
	switch {
	case f.Reader != nil:
		id := f.attachID
		if id == "" {
			id = f.Name
		}
		return json.Marshal("attach://" + id)
	case f.FileID != "":
		return json.Marshal(f.FileID)
	default:
		return json.Marshal(f.URL)
	}
}

func baseName(p string) string {
	for i := len(p) - 1; i >= 0; i-- {
		if p[i] == '/' || p[i] == '\\' {
			return p[i+1:]
		}
	}
	return p
}

// NewInlineQueryResultCachedAudio builds a *InlineQueryResultCachedAudio from its required fields.
func NewInlineQueryResultCachedAudio(id string, audioFileID string) *InlineQueryResultCachedAudio {
	return &InlineQueryResultCachedAudio{ID: id, AudioFileID: audioFileID}
}

// NewInlineQueryResultCachedDocument builds a *InlineQueryResultCachedDocument from its required fields.
func NewInlineQueryResultCachedDocument(id string, title string, documentFileID string) *InlineQueryResultCachedDocument {
	return &InlineQueryResultCachedDocument{ID: id, Title: title, DocumentFileID: documentFileID}
}

// NewInlineQueryResultCachedGIF builds a *InlineQueryResultCachedGIF from its required fields.
func NewInlineQueryResultCachedGIF(id string, gifFileID string) *InlineQueryResultCachedGIF {
	return &InlineQueryResultCachedGIF{ID: id, GIFFileID: gifFileID}
}

// NewInlineQueryResultCachedMpeg4GIF builds a *InlineQueryResultCachedMpeg4GIF from its required fields.
func NewInlineQueryResultCachedMpeg4GIF(id string, mpeg4FileID string) *InlineQueryResultCachedMpeg4GIF {
	return &InlineQueryResultCachedMpeg4GIF{ID: id, Mpeg4FileID: mpeg4FileID}
}

// NewInlineQueryResultCachedPhoto builds a *InlineQueryResultCachedPhoto from its required fields.
func NewInlineQueryResultCachedPhoto(id string, photoFileID string) *InlineQueryResultCachedPhoto {
	return &InlineQueryResultCachedPhoto{ID: id, PhotoFileID: photoFileID}
}

// NewInlineQueryResultCachedSticker builds a *InlineQueryResultCachedSticker from its required fields.
func NewInlineQueryResultCachedSticker(id string, stickerFileID string) *InlineQueryResultCachedSticker {
	return &InlineQueryResultCachedSticker{ID: id, StickerFileID: stickerFileID}
}

// NewInlineQueryResultCachedVideo builds a *InlineQueryResultCachedVideo from its required fields.
func NewInlineQueryResultCachedVideo(id string, videoFileID string, title string) *InlineQueryResultCachedVideo {
	return &InlineQueryResultCachedVideo{ID: id, VideoFileID: videoFileID, Title: title}
}

// NewInlineQueryResultCachedVoice builds a *InlineQueryResultCachedVoice from its required fields.
func NewInlineQueryResultCachedVoice(id string, voiceFileID string, title string) *InlineQueryResultCachedVoice {
	return &InlineQueryResultCachedVoice{ID: id, VoiceFileID: voiceFileID, Title: title}
}

// NewInlineQueryResultArticle builds a *InlineQueryResultArticle from its required fields.
func NewInlineQueryResultArticle(id string, title string, inputMessageContent InputMessageContent) *InlineQueryResultArticle {
	return &InlineQueryResultArticle{ID: id, Title: title, InputMessageContent: inputMessageContent}
}

// NewInlineQueryResultAudio builds a *InlineQueryResultAudio from its required fields.
func NewInlineQueryResultAudio(id string, audioURL string, title string) *InlineQueryResultAudio {
	return &InlineQueryResultAudio{ID: id, AudioURL: audioURL, Title: title}
}

// NewInlineQueryResultContact builds a *InlineQueryResultContact from its required fields.
func NewInlineQueryResultContact(id string, phoneNumber string, firstName string) *InlineQueryResultContact {
	return &InlineQueryResultContact{ID: id, PhoneNumber: phoneNumber, FirstName: firstName}
}

// NewInlineQueryResultGame builds a *InlineQueryResultGame from its required fields.
func NewInlineQueryResultGame(id string, gameShortName string) *InlineQueryResultGame {
	return &InlineQueryResultGame{ID: id, GameShortName: gameShortName}
}

// NewInlineQueryResultDocument builds a *InlineQueryResultDocument from its required fields.
func NewInlineQueryResultDocument(id string, title string, documentURL string, mimeType InlineQueryResultDocumentMimeType) *InlineQueryResultDocument {
	return &InlineQueryResultDocument{ID: id, Title: title, DocumentURL: documentURL, MimeType: mimeType}
}

// NewInlineQueryResultGIF builds a *InlineQueryResultGIF from its required fields.
func NewInlineQueryResultGIF(id string, gifURL string, thumbnailURL string) *InlineQueryResultGIF {
	return &InlineQueryResultGIF{ID: id, GIFURL: gifURL, ThumbnailURL: thumbnailURL}
}

// NewInlineQueryResultLocation builds a *InlineQueryResultLocation from its required fields.
func NewInlineQueryResultLocation(id string, latitude float64, longitude float64, title string) *InlineQueryResultLocation {
	return &InlineQueryResultLocation{ID: id, Latitude: latitude, Longitude: longitude, Title: title}
}

// NewInlineQueryResultMpeg4GIF builds a *InlineQueryResultMpeg4GIF from its required fields.
func NewInlineQueryResultMpeg4GIF(id string, mpeg4URL string, thumbnailURL string) *InlineQueryResultMpeg4GIF {
	return &InlineQueryResultMpeg4GIF{ID: id, Mpeg4URL: mpeg4URL, ThumbnailURL: thumbnailURL}
}

// NewInlineQueryResultPhoto builds a *InlineQueryResultPhoto from its required fields.
func NewInlineQueryResultPhoto(id string, photoURL string, thumbnailURL string) *InlineQueryResultPhoto {
	return &InlineQueryResultPhoto{ID: id, PhotoURL: photoURL, ThumbnailURL: thumbnailURL}
}

// NewInlineQueryResultVenue builds a *InlineQueryResultVenue from its required fields.
func NewInlineQueryResultVenue(id string, latitude float64, longitude float64, title string, address string) *InlineQueryResultVenue {
	return &InlineQueryResultVenue{ID: id, Latitude: latitude, Longitude: longitude, Title: title, Address: address}
}

// NewInlineQueryResultVideo builds a *InlineQueryResultVideo from its required fields.
func NewInlineQueryResultVideo(id string, videoURL string, mimeType string, thumbnailURL string, title string) *InlineQueryResultVideo {
	return &InlineQueryResultVideo{ID: id, VideoURL: videoURL, MimeType: mimeType, ThumbnailURL: thumbnailURL, Title: title}
}

// NewInlineQueryResultVoice builds a *InlineQueryResultVoice from its required fields.
func NewInlineQueryResultVoice(id string, voiceURL string, title string) *InlineQueryResultVoice {
	return &InlineQueryResultVoice{ID: id, VoiceURL: voiceURL, Title: title}
}

// NewInputMediaAnimation builds a *InputMediaAnimation from its required fields.
func NewInputMediaAnimation(media *InputFile) *InputMediaAnimation {
	return &InputMediaAnimation{Media: media}
}

// NewInputMediaAudio builds a *InputMediaAudio from its required fields.
func NewInputMediaAudio(media *InputFile) *InputMediaAudio {
	return &InputMediaAudio{Media: media}
}

// NewInputMediaDocument builds a *InputMediaDocument from its required fields.
func NewInputMediaDocument(media *InputFile) *InputMediaDocument {
	return &InputMediaDocument{Media: media}
}

// NewInputMediaLivePhoto builds a *InputMediaLivePhoto from its required fields.
func NewInputMediaLivePhoto(media *InputFile, photo *InputFile) *InputMediaLivePhoto {
	return &InputMediaLivePhoto{Media: media, Photo: photo}
}

// NewInputMediaPhoto builds a *InputMediaPhoto from its required fields.
func NewInputMediaPhoto(media *InputFile) *InputMediaPhoto {
	return &InputMediaPhoto{Media: media}
}

// NewInputMediaVideo builds a *InputMediaVideo from its required fields.
func NewInputMediaVideo(media *InputFile) *InputMediaVideo {
	return &InputMediaVideo{Media: media}
}

// NewInputMediaVoiceNote builds a *InputMediaVoiceNote from its required fields.
func NewInputMediaVoiceNote(media *InputFile) *InputMediaVoiceNote {
	return &InputMediaVoiceNote{Media: media}
}

// NewInputPaidMediaLivePhoto builds a *InputPaidMediaLivePhoto from its required fields.
func NewInputPaidMediaLivePhoto(media *InputFile, photo *InputFile) *InputPaidMediaLivePhoto {
	return &InputPaidMediaLivePhoto{Media: media, Photo: photo}
}

// NewInputPaidMediaPhoto builds a *InputPaidMediaPhoto from its required fields.
func NewInputPaidMediaPhoto(media *InputFile) *InputPaidMediaPhoto {
	return &InputPaidMediaPhoto{Media: media}
}

// NewInputPaidMediaVideo builds a *InputPaidMediaVideo from its required fields.
func NewInputPaidMediaVideo(media *InputFile) *InputPaidMediaVideo {
	return &InputPaidMediaVideo{Media: media}
}

// NewInputProfilePhotoStatic builds a *InputProfilePhotoStatic from its required fields.
func NewInputProfilePhotoStatic(photo *InputFile) *InputProfilePhotoStatic {
	return &InputProfilePhotoStatic{Photo: photo}
}

// NewInputProfilePhotoAnimated builds a *InputProfilePhotoAnimated from its required fields.
func NewInputProfilePhotoAnimated(animation *InputFile) *InputProfilePhotoAnimated {
	return &InputProfilePhotoAnimated{Animation: animation}
}

// NewInputRichBlockParagraph builds a *InputRichBlockParagraph from its required fields.
func NewInputRichBlockParagraph(text RichText) *InputRichBlockParagraph {
	return &InputRichBlockParagraph{Text: text}
}

// NewInputRichBlockSectionHeading builds a *InputRichBlockSectionHeading from its required fields.
func NewInputRichBlockSectionHeading(text RichText, size int64) *InputRichBlockSectionHeading {
	return &InputRichBlockSectionHeading{Text: text, Size: size}
}

// NewInputRichBlockPreformatted builds a *InputRichBlockPreformatted from its required fields.
func NewInputRichBlockPreformatted(text RichText) *InputRichBlockPreformatted {
	return &InputRichBlockPreformatted{Text: text}
}

// NewInputRichBlockFooter builds a *InputRichBlockFooter from its required fields.
func NewInputRichBlockFooter(text RichText) *InputRichBlockFooter {
	return &InputRichBlockFooter{Text: text}
}

// NewInputRichBlockDivider builds a *InputRichBlockDivider from its required fields.
func NewInputRichBlockDivider() *InputRichBlockDivider {
	return &InputRichBlockDivider{}
}

// NewInputRichBlockMathematicalExpression builds a *InputRichBlockMathematicalExpression from its required fields.
func NewInputRichBlockMathematicalExpression(expression string) *InputRichBlockMathematicalExpression {
	return &InputRichBlockMathematicalExpression{Expression: expression}
}

// NewInputRichBlockAnchor builds a *InputRichBlockAnchor from its required fields.
func NewInputRichBlockAnchor(name string) *InputRichBlockAnchor {
	return &InputRichBlockAnchor{Name: name}
}

// NewInputRichBlockList builds a *InputRichBlockList from its required fields.
func NewInputRichBlockList(items []InputRichBlockListItem) *InputRichBlockList {
	return &InputRichBlockList{Items: items}
}

// NewInputRichBlockBlockQuotation builds a *InputRichBlockBlockQuotation from its required fields.
func NewInputRichBlockBlockQuotation(blocks []InputRichBlock) *InputRichBlockBlockQuotation {
	return &InputRichBlockBlockQuotation{Blocks: blocks}
}

// NewInputRichBlockExpandableBlockQuotation builds a *InputRichBlockExpandableBlockQuotation from its required fields.
func NewInputRichBlockExpandableBlockQuotation(text RichText) *InputRichBlockExpandableBlockQuotation {
	return &InputRichBlockExpandableBlockQuotation{Text: text}
}

// NewInputRichBlockPullQuotation builds a *InputRichBlockPullQuotation from its required fields.
func NewInputRichBlockPullQuotation(text RichText) *InputRichBlockPullQuotation {
	return &InputRichBlockPullQuotation{Text: text}
}

// NewInputRichBlockCollage builds a *InputRichBlockCollage from its required fields.
func NewInputRichBlockCollage(blocks []InputRichBlock) *InputRichBlockCollage {
	return &InputRichBlockCollage{Blocks: blocks}
}

// NewInputRichBlockSlideshow builds a *InputRichBlockSlideshow from its required fields.
func NewInputRichBlockSlideshow(blocks []InputRichBlock) *InputRichBlockSlideshow {
	return &InputRichBlockSlideshow{Blocks: blocks}
}

// NewInputRichBlockTable builds a *InputRichBlockTable from its required fields.
func NewInputRichBlockTable(cells [][]RichBlockTableCell) *InputRichBlockTable {
	return &InputRichBlockTable{Cells: cells}
}

// NewInputRichBlockDetails builds a *InputRichBlockDetails from its required fields.
func NewInputRichBlockDetails(summary RichText, blocks []InputRichBlock) *InputRichBlockDetails {
	return &InputRichBlockDetails{Summary: summary, Blocks: blocks}
}

// NewInputRichBlockMap builds a *InputRichBlockMap from its required fields.
func NewInputRichBlockMap(location *Location) *InputRichBlockMap {
	return &InputRichBlockMap{Location: location}
}

// NewInputRichBlockButtons builds a *InputRichBlockButtons from its required fields.
func NewInputRichBlockButtons(buttons []RichMessageButton) *InputRichBlockButtons {
	return &InputRichBlockButtons{Buttons: buttons}
}

// NewInputRichBlockAnimation builds a *InputRichBlockAnimation from its required fields.
func NewInputRichBlockAnimation(animation *InputMediaAnimation) *InputRichBlockAnimation {
	return &InputRichBlockAnimation{Animation: animation}
}

// NewInputRichBlockAudio builds a *InputRichBlockAudio from its required fields.
func NewInputRichBlockAudio(audio *InputMediaAudio) *InputRichBlockAudio {
	return &InputRichBlockAudio{Audio: audio}
}

// NewInputRichBlockDocument builds a *InputRichBlockDocument from its required fields.
func NewInputRichBlockDocument(document *InputMediaDocument) *InputRichBlockDocument {
	return &InputRichBlockDocument{Document: document}
}

// NewInputRichBlockPhoto builds a *InputRichBlockPhoto from its required fields.
func NewInputRichBlockPhoto(photo *InputMediaPhoto) *InputRichBlockPhoto {
	return &InputRichBlockPhoto{Photo: photo}
}

// NewInputRichBlockVideo builds a *InputRichBlockVideo from its required fields.
func NewInputRichBlockVideo(video *InputMediaVideo) *InputRichBlockVideo {
	return &InputRichBlockVideo{Video: video}
}

// NewInputRichBlockVoiceNote builds a *InputRichBlockVoiceNote from its required fields.
func NewInputRichBlockVoiceNote(voiceNote *InputMediaVoiceNote) *InputRichBlockVoiceNote {
	return &InputRichBlockVoiceNote{VoiceNote: voiceNote}
}

// NewInputRichBlockThinking builds a *InputRichBlockThinking from its required fields.
func NewInputRichBlockThinking(text RichText) *InputRichBlockThinking {
	return &InputRichBlockThinking{Text: text}
}

// NewInputStoryContentPhoto builds a *InputStoryContentPhoto from its required fields.
func NewInputStoryContentPhoto(photo *InputFile) *InputStoryContentPhoto {
	return &InputStoryContentPhoto{Photo: photo}
}

// NewInputStoryContentVideo builds a *InputStoryContentVideo from its required fields.
func NewInputStoryContentVideo(video *InputFile) *InputStoryContentVideo {
	return &InputStoryContentVideo{Video: video}
}
