// Code generated by lumex; DO NOT EDIT.
//
// Source: https://core.telegram.org/bots/api
// Bot API version: 10.3

package lumex

import (
	"context"
	"encoding/json"
)

// ======================================================
// === Typed method wrappers (one per Bot API method) ===
// ======================================================

// GetUpdates calls the "getUpdates" Bot API method.
func (b *Bot) GetUpdates(ctx context.Context, opts ...GetUpdatesOpts) ([]Update, error) {
	req := &GetUpdatesRequest{}
	if len(opts) > 0 {
		req.GetUpdatesOpts = opts[0]
	}
	return Call[[]Update](ctx, b.BotClient, "getUpdates", req)
}

// SetWebhook calls the "setWebhook" Bot API method.
func (b *Bot) SetWebhook(ctx context.Context, url string, opts ...SetWebhookOpts) (bool, error) {
	req := &SetWebhookRequest{URL: url}
	if len(opts) > 0 {
		req.SetWebhookOpts = opts[0]
	}
	return Call[bool](ctx, b.BotClient, "setWebhook", req)
}

// DeleteWebhook calls the "deleteWebhook" Bot API method.
func (b *Bot) DeleteWebhook(ctx context.Context, opts ...DeleteWebhookOpts) (bool, error) {
	req := &DeleteWebhookRequest{}
	if len(opts) > 0 {
		req.DeleteWebhookOpts = opts[0]
	}
	return Call[bool](ctx, b.BotClient, "deleteWebhook", req)
}

// GetWebhookInfo calls the "getWebhookInfo" Bot API method.
func (b *Bot) GetWebhookInfo(ctx context.Context) (*WebhookInfo, error) {
	return Call[*WebhookInfo](ctx, b.BotClient, "getWebhookInfo", &GetWebhookInfoRequest{})
}

// GetMe calls the "getMe" Bot API method.
func (b *Bot) GetMe(ctx context.Context) (*User, error) {
	return Call[*User](ctx, b.BotClient, "getMe", &GetMeRequest{})
}

// LogOut calls the "logOut" Bot API method.
func (b *Bot) LogOut(ctx context.Context) (bool, error) {
	return Call[bool](ctx, b.BotClient, "logOut", &LogOutRequest{})
}

// Close calls the "close" Bot API method.
func (b *Bot) Close(ctx context.Context) (bool, error) {
	return Call[bool](ctx, b.BotClient, "close", &CloseRequest{})
}

// SendMessage calls the "sendMessage" Bot API method.
func (b *Bot) SendMessage(ctx context.Context, chatID int64, text string, opts ...SendMessageOpts) (*Message, error) {
	req := &SendMessageRequest{ChatID: chatID, Text: text}
	if len(opts) > 0 {
		req.SendMessageOpts = opts[0]
	}
	return Call[*Message](ctx, b.BotClient, "sendMessage", req)
}

// ForwardMessage calls the "forwardMessage" Bot API method.
func (b *Bot) ForwardMessage(ctx context.Context, chatID int64, fromChatID int64, messageID int64, opts ...ForwardMessageOpts) (*Message, error) {
	req := &ForwardMessageRequest{ChatID: chatID, FromChatID: fromChatID, MessageID: messageID}
	if len(opts) > 0 {
		req.ForwardMessageOpts = opts[0]
	}
	return Call[*Message](ctx, b.BotClient, "forwardMessage", req)
}

// ForwardMessages calls the "forwardMessages" Bot API method.
func (b *Bot) ForwardMessages(ctx context.Context, chatID int64, fromChatID int64, messageIDs []int64, opts ...ForwardMessagesOpts) ([]MessageID, error) {
	req := &ForwardMessagesRequest{ChatID: chatID, FromChatID: fromChatID, MessageIDs: messageIDs}
	if len(opts) > 0 {
		req.ForwardMessagesOpts = opts[0]
	}
	return Call[[]MessageID](ctx, b.BotClient, "forwardMessages", req)
}

// CopyMessage calls the "copyMessage" Bot API method.
func (b *Bot) CopyMessage(ctx context.Context, chatID int64, fromChatID int64, messageID int64, opts ...CopyMessageOpts) (*MessageID, error) {
	req := &CopyMessageRequest{ChatID: chatID, FromChatID: fromChatID, MessageID: messageID}
	if len(opts) > 0 {
		req.CopyMessageOpts = opts[0]
	}
	return Call[*MessageID](ctx, b.BotClient, "copyMessage", req)
}

// CopyMessages calls the "copyMessages" Bot API method.
func (b *Bot) CopyMessages(ctx context.Context, chatID int64, fromChatID int64, messageIDs []int64, opts ...CopyMessagesOpts) ([]MessageID, error) {
	req := &CopyMessagesRequest{ChatID: chatID, FromChatID: fromChatID, MessageIDs: messageIDs}
	if len(opts) > 0 {
		req.CopyMessagesOpts = opts[0]
	}
	return Call[[]MessageID](ctx, b.BotClient, "copyMessages", req)
}

// SendPhoto calls the "sendPhoto" Bot API method.
func (b *Bot) SendPhoto(ctx context.Context, chatID int64, photo *InputFile, opts ...SendPhotoOpts) (*Message, error) {
	req := &SendPhotoRequest{ChatID: chatID, Photo: photo}
	if len(opts) > 0 {
		req.SendPhotoOpts = opts[0]
	}
	return Call[*Message](ctx, b.BotClient, "sendPhoto", req)
}

// SendLivePhoto calls the "sendLivePhoto" Bot API method.
func (b *Bot) SendLivePhoto(ctx context.Context, chatID int64, livePhoto *InputFile, photo *InputFile, opts ...SendLivePhotoOpts) (*Message, error) {
	req := &SendLivePhotoRequest{ChatID: chatID, LivePhoto: livePhoto, Photo: photo}
	if len(opts) > 0 {
		req.SendLivePhotoOpts = opts[0]
	}
	return Call[*Message](ctx, b.BotClient, "sendLivePhoto", req)
}

// SendAudio calls the "sendAudio" Bot API method.
func (b *Bot) SendAudio(ctx context.Context, chatID int64, audio *InputFile, opts ...SendAudioOpts) (*Message, error) {
	req := &SendAudioRequest{ChatID: chatID, Audio: audio}
	if len(opts) > 0 {
		req.SendAudioOpts = opts[0]
	}
	return Call[*Message](ctx, b.BotClient, "sendAudio", req)
}

// SendDocument calls the "sendDocument" Bot API method.
func (b *Bot) SendDocument(ctx context.Context, chatID int64, document *InputFile, opts ...SendDocumentOpts) (*Message, error) {
	req := &SendDocumentRequest{ChatID: chatID, Document: document}
	if len(opts) > 0 {
		req.SendDocumentOpts = opts[0]
	}
	return Call[*Message](ctx, b.BotClient, "sendDocument", req)
}

// SendVideo calls the "sendVideo" Bot API method.
func (b *Bot) SendVideo(ctx context.Context, chatID int64, video *InputFile, opts ...SendVideoOpts) (*Message, error) {
	req := &SendVideoRequest{ChatID: chatID, Video: video}
	if len(opts) > 0 {
		req.SendVideoOpts = opts[0]
	}
	return Call[*Message](ctx, b.BotClient, "sendVideo", req)
}

// SendAnimation calls the "sendAnimation" Bot API method.
func (b *Bot) SendAnimation(ctx context.Context, chatID int64, animation *InputFile, opts ...SendAnimationOpts) (*Message, error) {
	req := &SendAnimationRequest{ChatID: chatID, Animation: animation}
	if len(opts) > 0 {
		req.SendAnimationOpts = opts[0]
	}
	return Call[*Message](ctx, b.BotClient, "sendAnimation", req)
}

// SendVoice calls the "sendVoice" Bot API method.
func (b *Bot) SendVoice(ctx context.Context, chatID int64, voice *InputFile, opts ...SendVoiceOpts) (*Message, error) {
	req := &SendVoiceRequest{ChatID: chatID, Voice: voice}
	if len(opts) > 0 {
		req.SendVoiceOpts = opts[0]
	}
	return Call[*Message](ctx, b.BotClient, "sendVoice", req)
}

// SendVideoNote calls the "sendVideoNote" Bot API method.
func (b *Bot) SendVideoNote(ctx context.Context, chatID int64, videoNote *InputFile, opts ...SendVideoNoteOpts) (*Message, error) {
	req := &SendVideoNoteRequest{ChatID: chatID, VideoNote: videoNote}
	if len(opts) > 0 {
		req.SendVideoNoteOpts = opts[0]
	}
	return Call[*Message](ctx, b.BotClient, "sendVideoNote", req)
}

// SendPaidMedia calls the "sendPaidMedia" Bot API method.
func (b *Bot) SendPaidMedia(ctx context.Context, chatID int64, starCount int64, media []InputPaidMedia, opts ...SendPaidMediaOpts) (*Message, error) {
	req := &SendPaidMediaRequest{ChatID: chatID, StarCount: starCount, Media: media}
	if len(opts) > 0 {
		req.SendPaidMediaOpts = opts[0]
	}
	return Call[*Message](ctx, b.BotClient, "sendPaidMedia", req)
}

// SendMediaGroup calls the "sendMediaGroup" Bot API method.
func (b *Bot) SendMediaGroup(ctx context.Context, chatID int64, media []InputMedia, opts ...SendMediaGroupOpts) ([]Message, error) {
	req := &SendMediaGroupRequest{ChatID: chatID, Media: media}
	if len(opts) > 0 {
		req.SendMediaGroupOpts = opts[0]
	}
	return Call[[]Message](ctx, b.BotClient, "sendMediaGroup", req)
}

// SendLocation calls the "sendLocation" Bot API method.
func (b *Bot) SendLocation(ctx context.Context, chatID int64, latitude float64, longitude float64, opts ...SendLocationOpts) (*Message, error) {
	req := &SendLocationRequest{ChatID: chatID, Latitude: latitude, Longitude: longitude}
	if len(opts) > 0 {
		req.SendLocationOpts = opts[0]
	}
	return Call[*Message](ctx, b.BotClient, "sendLocation", req)
}

// SendVenue calls the "sendVenue" Bot API method.
func (b *Bot) SendVenue(ctx context.Context, chatID int64, latitude float64, longitude float64, title string, address string, opts ...SendVenueOpts) (*Message, error) {
	req := &SendVenueRequest{ChatID: chatID, Latitude: latitude, Longitude: longitude, Title: title, Address: address}
	if len(opts) > 0 {
		req.SendVenueOpts = opts[0]
	}
	return Call[*Message](ctx, b.BotClient, "sendVenue", req)
}

// SendContact calls the "sendContact" Bot API method.
func (b *Bot) SendContact(ctx context.Context, chatID int64, phoneNumber string, firstName string, opts ...SendContactOpts) (*Message, error) {
	req := &SendContactRequest{ChatID: chatID, PhoneNumber: phoneNumber, FirstName: firstName}
	if len(opts) > 0 {
		req.SendContactOpts = opts[0]
	}
	return Call[*Message](ctx, b.BotClient, "sendContact", req)
}

// SendPoll calls the "sendPoll" Bot API method.
func (b *Bot) SendPoll(ctx context.Context, chatID int64, question string, options []InputPollOption, opts ...SendPollOpts) (*Message, error) {
	req := &SendPollRequest{ChatID: chatID, Question: question, Options: options}
	if len(opts) > 0 {
		req.SendPollOpts = opts[0]
	}
	return Call[*Message](ctx, b.BotClient, "sendPoll", req)
}

// SendChecklist calls the "sendChecklist" Bot API method.
func (b *Bot) SendChecklist(ctx context.Context, businessConnectionID string, chatID int64, checklist *InputChecklist, opts ...SendChecklistOpts) (*Message, error) {
	req := &SendChecklistRequest{BusinessConnectionID: businessConnectionID, ChatID: chatID, Checklist: checklist}
	if len(opts) > 0 {
		req.SendChecklistOpts = opts[0]
	}
	return Call[*Message](ctx, b.BotClient, "sendChecklist", req)
}

// SendDice calls the "sendDice" Bot API method.
func (b *Bot) SendDice(ctx context.Context, chatID int64, opts ...SendDiceOpts) (*Message, error) {
	req := &SendDiceRequest{ChatID: chatID}
	if len(opts) > 0 {
		req.SendDiceOpts = opts[0]
	}
	return Call[*Message](ctx, b.BotClient, "sendDice", req)
}

// SendMessageDraft calls the "sendMessageDraft" Bot API method.
func (b *Bot) SendMessageDraft(ctx context.Context, chatID int64, draftID int64, opts ...SendMessageDraftOpts) (bool, error) {
	req := &SendMessageDraftRequest{ChatID: chatID, DraftID: draftID}
	if len(opts) > 0 {
		req.SendMessageDraftOpts = opts[0]
	}
	return Call[bool](ctx, b.BotClient, "sendMessageDraft", req)
}

// SendChatAction calls the "sendChatAction" Bot API method.
func (b *Bot) SendChatAction(ctx context.Context, chatID int64, action string, opts ...SendChatActionOpts) (bool, error) {
	req := &SendChatActionRequest{ChatID: chatID, Action: action}
	if len(opts) > 0 {
		req.SendChatActionOpts = opts[0]
	}
	return Call[bool](ctx, b.BotClient, "sendChatAction", req)
}

// SetMessageReaction calls the "setMessageReaction" Bot API method.
func (b *Bot) SetMessageReaction(ctx context.Context, chatID int64, messageID int64, opts ...SetMessageReactionOpts) (bool, error) {
	req := &SetMessageReactionRequest{ChatID: chatID, MessageID: messageID}
	if len(opts) > 0 {
		req.SetMessageReactionOpts = opts[0]
	}
	return Call[bool](ctx, b.BotClient, "setMessageReaction", req)
}

// GetUserProfilePhotos calls the "getUserProfilePhotos" Bot API method.
func (b *Bot) GetUserProfilePhotos(ctx context.Context, userID int64, opts ...GetUserProfilePhotosOpts) (*UserProfilePhotos, error) {
	req := &GetUserProfilePhotosRequest{UserID: userID}
	if len(opts) > 0 {
		req.GetUserProfilePhotosOpts = opts[0]
	}
	return Call[*UserProfilePhotos](ctx, b.BotClient, "getUserProfilePhotos", req)
}

// GetUserProfileAudios calls the "getUserProfileAudios" Bot API method.
func (b *Bot) GetUserProfileAudios(ctx context.Context, userID int64, opts ...GetUserProfileAudiosOpts) (*UserProfileAudios, error) {
	req := &GetUserProfileAudiosRequest{UserID: userID}
	if len(opts) > 0 {
		req.GetUserProfileAudiosOpts = opts[0]
	}
	return Call[*UserProfileAudios](ctx, b.BotClient, "getUserProfileAudios", req)
}

// SetUserEmojiStatus calls the "setUserEmojiStatus" Bot API method.
func (b *Bot) SetUserEmojiStatus(ctx context.Context, userID int64, opts ...SetUserEmojiStatusOpts) (bool, error) {
	req := &SetUserEmojiStatusRequest{UserID: userID}
	if len(opts) > 0 {
		req.SetUserEmojiStatusOpts = opts[0]
	}
	return Call[bool](ctx, b.BotClient, "setUserEmojiStatus", req)
}

// GetFile calls the "getFile" Bot API method.
func (b *Bot) GetFile(ctx context.Context, fileID string) (*File, error) {
	return Call[*File](ctx, b.BotClient, "getFile", &GetFileRequest{FileID: fileID})
}

// BanChatMember calls the "banChatMember" Bot API method.
func (b *Bot) BanChatMember(ctx context.Context, chatID int64, userID int64, opts ...BanChatMemberOpts) (bool, error) {
	req := &BanChatMemberRequest{ChatID: chatID, UserID: userID}
	if len(opts) > 0 {
		req.BanChatMemberOpts = opts[0]
	}
	return Call[bool](ctx, b.BotClient, "banChatMember", req)
}

// UnbanChatMember calls the "unbanChatMember" Bot API method.
func (b *Bot) UnbanChatMember(ctx context.Context, chatID int64, userID int64, opts ...UnbanChatMemberOpts) (bool, error) {
	req := &UnbanChatMemberRequest{ChatID: chatID, UserID: userID}
	if len(opts) > 0 {
		req.UnbanChatMemberOpts = opts[0]
	}
	return Call[bool](ctx, b.BotClient, "unbanChatMember", req)
}

// RestrictChatMember calls the "restrictChatMember" Bot API method.
func (b *Bot) RestrictChatMember(ctx context.Context, chatID int64, userID int64, permissions *ChatPermissions, opts ...RestrictChatMemberOpts) (bool, error) {
	req := &RestrictChatMemberRequest{ChatID: chatID, UserID: userID, Permissions: permissions}
	if len(opts) > 0 {
		req.RestrictChatMemberOpts = opts[0]
	}
	return Call[bool](ctx, b.BotClient, "restrictChatMember", req)
}

// PromoteChatMember calls the "promoteChatMember" Bot API method.
func (b *Bot) PromoteChatMember(ctx context.Context, chatID int64, userID int64, opts ...PromoteChatMemberOpts) (bool, error) {
	req := &PromoteChatMemberRequest{ChatID: chatID, UserID: userID}
	if len(opts) > 0 {
		req.PromoteChatMemberOpts = opts[0]
	}
	return Call[bool](ctx, b.BotClient, "promoteChatMember", req)
}

// SetChatAdministratorCustomTitle calls the "setChatAdministratorCustomTitle" Bot API method.
func (b *Bot) SetChatAdministratorCustomTitle(ctx context.Context, chatID int64, userID int64, customTitle string) (bool, error) {
	return Call[bool](ctx, b.BotClient, "setChatAdministratorCustomTitle", &SetChatAdministratorCustomTitleRequest{ChatID: chatID, UserID: userID, CustomTitle: customTitle})
}

// SetChatMemberTag calls the "setChatMemberTag" Bot API method.
func (b *Bot) SetChatMemberTag(ctx context.Context, chatID int64, userID int64, opts ...SetChatMemberTagOpts) (bool, error) {
	req := &SetChatMemberTagRequest{ChatID: chatID, UserID: userID}
	if len(opts) > 0 {
		req.SetChatMemberTagOpts = opts[0]
	}
	return Call[bool](ctx, b.BotClient, "setChatMemberTag", req)
}

// BanChatSenderChat calls the "banChatSenderChat" Bot API method.
func (b *Bot) BanChatSenderChat(ctx context.Context, chatID int64, senderChatID int64) (bool, error) {
	return Call[bool](ctx, b.BotClient, "banChatSenderChat", &BanChatSenderChatRequest{ChatID: chatID, SenderChatID: senderChatID})
}

// UnbanChatSenderChat calls the "unbanChatSenderChat" Bot API method.
func (b *Bot) UnbanChatSenderChat(ctx context.Context, chatID int64, senderChatID int64) (bool, error) {
	return Call[bool](ctx, b.BotClient, "unbanChatSenderChat", &UnbanChatSenderChatRequest{ChatID: chatID, SenderChatID: senderChatID})
}

// SetChatPermissions calls the "setChatPermissions" Bot API method.
func (b *Bot) SetChatPermissions(ctx context.Context, chatID int64, permissions *ChatPermissions, opts ...SetChatPermissionsOpts) (bool, error) {
	req := &SetChatPermissionsRequest{ChatID: chatID, Permissions: permissions}
	if len(opts) > 0 {
		req.SetChatPermissionsOpts = opts[0]
	}
	return Call[bool](ctx, b.BotClient, "setChatPermissions", req)
}

// ExportChatInviteLink calls the "exportChatInviteLink" Bot API method.
func (b *Bot) ExportChatInviteLink(ctx context.Context, chatID int64) (string, error) {
	return Call[string](ctx, b.BotClient, "exportChatInviteLink", &ExportChatInviteLinkRequest{ChatID: chatID})
}

// CreateChatInviteLink calls the "createChatInviteLink" Bot API method.
func (b *Bot) CreateChatInviteLink(ctx context.Context, chatID int64, opts ...CreateChatInviteLinkOpts) (*ChatInviteLink, error) {
	req := &CreateChatInviteLinkRequest{ChatID: chatID}
	if len(opts) > 0 {
		req.CreateChatInviteLinkOpts = opts[0]
	}
	return Call[*ChatInviteLink](ctx, b.BotClient, "createChatInviteLink", req)
}

// EditChatInviteLink calls the "editChatInviteLink" Bot API method.
func (b *Bot) EditChatInviteLink(ctx context.Context, chatID int64, inviteLink string, opts ...EditChatInviteLinkOpts) (*ChatInviteLink, error) {
	req := &EditChatInviteLinkRequest{ChatID: chatID, InviteLink: inviteLink}
	if len(opts) > 0 {
		req.EditChatInviteLinkOpts = opts[0]
	}
	return Call[*ChatInviteLink](ctx, b.BotClient, "editChatInviteLink", req)
}

// CreateChatSubscriptionInviteLink calls the "createChatSubscriptionInviteLink" Bot API method.
func (b *Bot) CreateChatSubscriptionInviteLink(ctx context.Context, chatID int64, subscriptionPeriod int64, subscriptionPrice int64, opts ...CreateChatSubscriptionInviteLinkOpts) (*ChatInviteLink, error) {
	req := &CreateChatSubscriptionInviteLinkRequest{ChatID: chatID, SubscriptionPeriod: subscriptionPeriod, SubscriptionPrice: subscriptionPrice}
	if len(opts) > 0 {
		req.CreateChatSubscriptionInviteLinkOpts = opts[0]
	}
	return Call[*ChatInviteLink](ctx, b.BotClient, "createChatSubscriptionInviteLink", req)
}

// EditChatSubscriptionInviteLink calls the "editChatSubscriptionInviteLink" Bot API method.
func (b *Bot) EditChatSubscriptionInviteLink(ctx context.Context, chatID int64, inviteLink string, opts ...EditChatSubscriptionInviteLinkOpts) (*ChatInviteLink, error) {
	req := &EditChatSubscriptionInviteLinkRequest{ChatID: chatID, InviteLink: inviteLink}
	if len(opts) > 0 {
		req.EditChatSubscriptionInviteLinkOpts = opts[0]
	}
	return Call[*ChatInviteLink](ctx, b.BotClient, "editChatSubscriptionInviteLink", req)
}

// RevokeChatInviteLink calls the "revokeChatInviteLink" Bot API method.
func (b *Bot) RevokeChatInviteLink(ctx context.Context, chatID int64, inviteLink string) (*ChatInviteLink, error) {
	return Call[*ChatInviteLink](ctx, b.BotClient, "revokeChatInviteLink", &RevokeChatInviteLinkRequest{ChatID: chatID, InviteLink: inviteLink})
}

// ApproveChatJoinRequest calls the "approveChatJoinRequest" Bot API method.
func (b *Bot) ApproveChatJoinRequest(ctx context.Context, chatID int64, userID int64) (bool, error) {
	return Call[bool](ctx, b.BotClient, "approveChatJoinRequest", &ApproveChatJoinRequestRequest{ChatID: chatID, UserID: userID})
}

// DeclineChatJoinRequest calls the "declineChatJoinRequest" Bot API method.
func (b *Bot) DeclineChatJoinRequest(ctx context.Context, chatID int64, userID int64) (bool, error) {
	return Call[bool](ctx, b.BotClient, "declineChatJoinRequest", &DeclineChatJoinRequestRequest{ChatID: chatID, UserID: userID})
}

// AnswerChatJoinRequestQuery calls the "answerChatJoinRequestQuery" Bot API method.
func (b *Bot) AnswerChatJoinRequestQuery(ctx context.Context, chatJoinRequestQueryID string, result AnswerChatJoinRequestQueryResult) (bool, error) {
	return Call[bool](ctx, b.BotClient, "answerChatJoinRequestQuery", &AnswerChatJoinRequestQueryRequest{ChatJoinRequestQueryID: chatJoinRequestQueryID, Result: result})
}

// SendChatJoinRequestWebApp calls the "sendChatJoinRequestWebApp" Bot API method.
func (b *Bot) SendChatJoinRequestWebApp(ctx context.Context, chatJoinRequestQueryID string, webAppURL string) (bool, error) {
	return Call[bool](ctx, b.BotClient, "sendChatJoinRequestWebApp", &SendChatJoinRequestWebAppRequest{ChatJoinRequestQueryID: chatJoinRequestQueryID, WebAppURL: webAppURL})
}

// SetChatPhoto calls the "setChatPhoto" Bot API method.
func (b *Bot) SetChatPhoto(ctx context.Context, chatID int64, photo *InputFile) (bool, error) {
	return Call[bool](ctx, b.BotClient, "setChatPhoto", &SetChatPhotoRequest{ChatID: chatID, Photo: photo})
}

// DeleteChatPhoto calls the "deleteChatPhoto" Bot API method.
func (b *Bot) DeleteChatPhoto(ctx context.Context, chatID int64) (bool, error) {
	return Call[bool](ctx, b.BotClient, "deleteChatPhoto", &DeleteChatPhotoRequest{ChatID: chatID})
}

// SetChatTitle calls the "setChatTitle" Bot API method.
func (b *Bot) SetChatTitle(ctx context.Context, chatID int64, title string) (bool, error) {
	return Call[bool](ctx, b.BotClient, "setChatTitle", &SetChatTitleRequest{ChatID: chatID, Title: title})
}

// SetChatDescription calls the "setChatDescription" Bot API method.
func (b *Bot) SetChatDescription(ctx context.Context, chatID int64, opts ...SetChatDescriptionOpts) (bool, error) {
	req := &SetChatDescriptionRequest{ChatID: chatID}
	if len(opts) > 0 {
		req.SetChatDescriptionOpts = opts[0]
	}
	return Call[bool](ctx, b.BotClient, "setChatDescription", req)
}

// PinChatMessage calls the "pinChatMessage" Bot API method.
func (b *Bot) PinChatMessage(ctx context.Context, chatID int64, messageID int64, opts ...PinChatMessageOpts) (bool, error) {
	req := &PinChatMessageRequest{ChatID: chatID, MessageID: messageID}
	if len(opts) > 0 {
		req.PinChatMessageOpts = opts[0]
	}
	return Call[bool](ctx, b.BotClient, "pinChatMessage", req)
}

// UnpinChatMessage calls the "unpinChatMessage" Bot API method.
func (b *Bot) UnpinChatMessage(ctx context.Context, chatID int64, opts ...UnpinChatMessageOpts) (bool, error) {
	req := &UnpinChatMessageRequest{ChatID: chatID}
	if len(opts) > 0 {
		req.UnpinChatMessageOpts = opts[0]
	}
	return Call[bool](ctx, b.BotClient, "unpinChatMessage", req)
}

// UnpinAllChatMessages calls the "unpinAllChatMessages" Bot API method.
func (b *Bot) UnpinAllChatMessages(ctx context.Context, chatID int64) (bool, error) {
	return Call[bool](ctx, b.BotClient, "unpinAllChatMessages", &UnpinAllChatMessagesRequest{ChatID: chatID})
}

// LeaveChat calls the "leaveChat" Bot API method.
func (b *Bot) LeaveChat(ctx context.Context, chatID int64) (bool, error) {
	return Call[bool](ctx, b.BotClient, "leaveChat", &LeaveChatRequest{ChatID: chatID})
}

// GetChat calls the "getChat" Bot API method.
func (b *Bot) GetChat(ctx context.Context, chatID int64) (*ChatFullInfo, error) {
	return Call[*ChatFullInfo](ctx, b.BotClient, "getChat", &GetChatRequest{ChatID: chatID})
}

// GetChatAdministrators calls the "getChatAdministrators" Bot API method.
func (b *Bot) GetChatAdministrators(ctx context.Context, chatID int64, opts ...GetChatAdministratorsOpts) ([]ChatMember, error) {
	req := &GetChatAdministratorsRequest{ChatID: chatID}
	if len(opts) > 0 {
		req.GetChatAdministratorsOpts = opts[0]
	}
	return Call[[]ChatMember](ctx, b.BotClient, "getChatAdministrators", req)
}

// GetChatMemberCount calls the "getChatMemberCount" Bot API method.
func (b *Bot) GetChatMemberCount(ctx context.Context, chatID int64) (int64, error) {
	return Call[int64](ctx, b.BotClient, "getChatMemberCount", &GetChatMemberCountRequest{ChatID: chatID})
}

// GetChatMember calls the "getChatMember" Bot API method.
func (b *Bot) GetChatMember(ctx context.Context, chatID int64, userID int64) (ChatMember, error) {
	raw, err := b.BotClient.RequestWithContext(ctx, "getChatMember", &GetChatMemberRequest{ChatID: chatID, UserID: userID})
	if err != nil {
		return nil, err
	}
	return DecodeChatMember(raw)
}

// GetUserPersonalChatMessages calls the "getUserPersonalChatMessages" Bot API method.
func (b *Bot) GetUserPersonalChatMessages(ctx context.Context, userID int64, limit int64) ([]Message, error) {
	return Call[[]Message](ctx, b.BotClient, "getUserPersonalChatMessages", &GetUserPersonalChatMessagesRequest{UserID: userID, Limit: limit})
}

// SetChatStickerSet calls the "setChatStickerSet" Bot API method.
func (b *Bot) SetChatStickerSet(ctx context.Context, chatID int64, stickerSetName string) (bool, error) {
	return Call[bool](ctx, b.BotClient, "setChatStickerSet", &SetChatStickerSetRequest{ChatID: chatID, StickerSetName: stickerSetName})
}

// DeleteChatStickerSet calls the "deleteChatStickerSet" Bot API method.
func (b *Bot) DeleteChatStickerSet(ctx context.Context, chatID int64) (bool, error) {
	return Call[bool](ctx, b.BotClient, "deleteChatStickerSet", &DeleteChatStickerSetRequest{ChatID: chatID})
}

// GetForumTopicIconStickers calls the "getForumTopicIconStickers" Bot API method.
func (b *Bot) GetForumTopicIconStickers(ctx context.Context) ([]Sticker, error) {
	return Call[[]Sticker](ctx, b.BotClient, "getForumTopicIconStickers", &GetForumTopicIconStickersRequest{})
}

// CreateForumTopic calls the "createForumTopic" Bot API method.
func (b *Bot) CreateForumTopic(ctx context.Context, chatID int64, name string, opts ...CreateForumTopicOpts) (*ForumTopic, error) {
	req := &CreateForumTopicRequest{ChatID: chatID, Name: name}
	if len(opts) > 0 {
		req.CreateForumTopicOpts = opts[0]
	}
	return Call[*ForumTopic](ctx, b.BotClient, "createForumTopic", req)
}

// EditForumTopic calls the "editForumTopic" Bot API method.
func (b *Bot) EditForumTopic(ctx context.Context, chatID int64, messageThreadID int64, opts ...EditForumTopicOpts) (bool, error) {
	req := &EditForumTopicRequest{ChatID: chatID, MessageThreadID: messageThreadID}
	if len(opts) > 0 {
		req.EditForumTopicOpts = opts[0]
	}
	return Call[bool](ctx, b.BotClient, "editForumTopic", req)
}

// CloseForumTopic calls the "closeForumTopic" Bot API method.
func (b *Bot) CloseForumTopic(ctx context.Context, chatID int64, messageThreadID int64) (bool, error) {
	return Call[bool](ctx, b.BotClient, "closeForumTopic", &CloseForumTopicRequest{ChatID: chatID, MessageThreadID: messageThreadID})
}

// ReopenForumTopic calls the "reopenForumTopic" Bot API method.
func (b *Bot) ReopenForumTopic(ctx context.Context, chatID int64, messageThreadID int64) (bool, error) {
	return Call[bool](ctx, b.BotClient, "reopenForumTopic", &ReopenForumTopicRequest{ChatID: chatID, MessageThreadID: messageThreadID})
}

// DeleteForumTopic calls the "deleteForumTopic" Bot API method.
func (b *Bot) DeleteForumTopic(ctx context.Context, chatID int64, messageThreadID int64) (bool, error) {
	return Call[bool](ctx, b.BotClient, "deleteForumTopic", &DeleteForumTopicRequest{ChatID: chatID, MessageThreadID: messageThreadID})
}

// UnpinAllForumTopicMessages calls the "unpinAllForumTopicMessages" Bot API method.
func (b *Bot) UnpinAllForumTopicMessages(ctx context.Context, chatID int64, messageThreadID int64) (bool, error) {
	return Call[bool](ctx, b.BotClient, "unpinAllForumTopicMessages", &UnpinAllForumTopicMessagesRequest{ChatID: chatID, MessageThreadID: messageThreadID})
}

// EditGeneralForumTopic calls the "editGeneralForumTopic" Bot API method.
func (b *Bot) EditGeneralForumTopic(ctx context.Context, chatID int64, name string) (bool, error) {
	return Call[bool](ctx, b.BotClient, "editGeneralForumTopic", &EditGeneralForumTopicRequest{ChatID: chatID, Name: name})
}

// CloseGeneralForumTopic calls the "closeGeneralForumTopic" Bot API method.
func (b *Bot) CloseGeneralForumTopic(ctx context.Context, chatID int64) (bool, error) {
	return Call[bool](ctx, b.BotClient, "closeGeneralForumTopic", &CloseGeneralForumTopicRequest{ChatID: chatID})
}

// ReopenGeneralForumTopic calls the "reopenGeneralForumTopic" Bot API method.
func (b *Bot) ReopenGeneralForumTopic(ctx context.Context, chatID int64) (bool, error) {
	return Call[bool](ctx, b.BotClient, "reopenGeneralForumTopic", &ReopenGeneralForumTopicRequest{ChatID: chatID})
}

// HideGeneralForumTopic calls the "hideGeneralForumTopic" Bot API method.
func (b *Bot) HideGeneralForumTopic(ctx context.Context, chatID int64) (bool, error) {
	return Call[bool](ctx, b.BotClient, "hideGeneralForumTopic", &HideGeneralForumTopicRequest{ChatID: chatID})
}

// UnhideGeneralForumTopic calls the "unhideGeneralForumTopic" Bot API method.
func (b *Bot) UnhideGeneralForumTopic(ctx context.Context, chatID int64) (bool, error) {
	return Call[bool](ctx, b.BotClient, "unhideGeneralForumTopic", &UnhideGeneralForumTopicRequest{ChatID: chatID})
}

// UnpinAllGeneralForumTopicMessages calls the "unpinAllGeneralForumTopicMessages" Bot API method.
func (b *Bot) UnpinAllGeneralForumTopicMessages(ctx context.Context, chatID int64) (bool, error) {
	return Call[bool](ctx, b.BotClient, "unpinAllGeneralForumTopicMessages", &UnpinAllGeneralForumTopicMessagesRequest{ChatID: chatID})
}

// AnswerCallbackQuery calls the "answerCallbackQuery" Bot API method.
func (b *Bot) AnswerCallbackQuery(ctx context.Context, callbackQueryID string, opts ...AnswerCallbackQueryOpts) (bool, error) {
	req := &AnswerCallbackQueryRequest{CallbackQueryID: callbackQueryID}
	if len(opts) > 0 {
		req.AnswerCallbackQueryOpts = opts[0]
	}
	return Call[bool](ctx, b.BotClient, "answerCallbackQuery", req)
}

// AnswerGuestQuery calls the "answerGuestQuery" Bot API method.
func (b *Bot) AnswerGuestQuery(ctx context.Context, guestQueryID string, result InlineQueryResult) (*SentGuestMessage, error) {
	return Call[*SentGuestMessage](ctx, b.BotClient, "answerGuestQuery", &AnswerGuestQueryRequest{GuestQueryID: guestQueryID, Result: result})
}

// GetUserChatBoosts calls the "getUserChatBoosts" Bot API method.
func (b *Bot) GetUserChatBoosts(ctx context.Context, chatID int64, userID int64) (*UserChatBoosts, error) {
	return Call[*UserChatBoosts](ctx, b.BotClient, "getUserChatBoosts", &GetUserChatBoostsRequest{ChatID: chatID, UserID: userID})
}

// GetBusinessConnection calls the "getBusinessConnection" Bot API method.
func (b *Bot) GetBusinessConnection(ctx context.Context, businessConnectionID string) (*BusinessConnection, error) {
	return Call[*BusinessConnection](ctx, b.BotClient, "getBusinessConnection", &GetBusinessConnectionRequest{BusinessConnectionID: businessConnectionID})
}

// GetManagedBotToken calls the "getManagedBotToken" Bot API method.
func (b *Bot) GetManagedBotToken(ctx context.Context, userID int64) (string, error) {
	return Call[string](ctx, b.BotClient, "getManagedBotToken", &GetManagedBotTokenRequest{UserID: userID})
}

// ReplaceManagedBotToken calls the "replaceManagedBotToken" Bot API method.
func (b *Bot) ReplaceManagedBotToken(ctx context.Context, userID int64) (string, error) {
	return Call[string](ctx, b.BotClient, "replaceManagedBotToken", &ReplaceManagedBotTokenRequest{UserID: userID})
}

// GetManagedBotAccessSettings calls the "getManagedBotAccessSettings" Bot API method.
func (b *Bot) GetManagedBotAccessSettings(ctx context.Context, userID int64) (*BotAccessSettings, error) {
	return Call[*BotAccessSettings](ctx, b.BotClient, "getManagedBotAccessSettings", &GetManagedBotAccessSettingsRequest{UserID: userID})
}

// SetManagedBotAccessSettings calls the "setManagedBotAccessSettings" Bot API method.
func (b *Bot) SetManagedBotAccessSettings(ctx context.Context, userID int64, isAccessRestricted bool, opts ...SetManagedBotAccessSettingsOpts) (bool, error) {
	req := &SetManagedBotAccessSettingsRequest{UserID: userID, IsAccessRestricted: isAccessRestricted}
	if len(opts) > 0 {
		req.SetManagedBotAccessSettingsOpts = opts[0]
	}
	return Call[bool](ctx, b.BotClient, "setManagedBotAccessSettings", req)
}

// SetMyCommands calls the "setMyCommands" Bot API method.
func (b *Bot) SetMyCommands(ctx context.Context, commands []BotCommand, opts ...SetMyCommandsOpts) (bool, error) {
	req := &SetMyCommandsRequest{Commands: commands}
	if len(opts) > 0 {
		req.SetMyCommandsOpts = opts[0]
	}
	return Call[bool](ctx, b.BotClient, "setMyCommands", req)
}

// DeleteMyCommands calls the "deleteMyCommands" Bot API method.
func (b *Bot) DeleteMyCommands(ctx context.Context, opts ...DeleteMyCommandsOpts) (bool, error) {
	req := &DeleteMyCommandsRequest{}
	if len(opts) > 0 {
		req.DeleteMyCommandsOpts = opts[0]
	}
	return Call[bool](ctx, b.BotClient, "deleteMyCommands", req)
}

// GetMyCommands calls the "getMyCommands" Bot API method.
func (b *Bot) GetMyCommands(ctx context.Context, opts ...GetMyCommandsOpts) ([]BotCommand, error) {
	req := &GetMyCommandsRequest{}
	if len(opts) > 0 {
		req.GetMyCommandsOpts = opts[0]
	}
	return Call[[]BotCommand](ctx, b.BotClient, "getMyCommands", req)
}

// SetMyName calls the "setMyName" Bot API method.
func (b *Bot) SetMyName(ctx context.Context, opts ...SetMyNameOpts) (bool, error) {
	req := &SetMyNameRequest{}
	if len(opts) > 0 {
		req.SetMyNameOpts = opts[0]
	}
	return Call[bool](ctx, b.BotClient, "setMyName", req)
}

// GetMyName calls the "getMyName" Bot API method.
func (b *Bot) GetMyName(ctx context.Context, opts ...GetMyNameOpts) (*BotName, error) {
	req := &GetMyNameRequest{}
	if len(opts) > 0 {
		req.GetMyNameOpts = opts[0]
	}
	return Call[*BotName](ctx, b.BotClient, "getMyName", req)
}

// SetMyDescription calls the "setMyDescription" Bot API method.
func (b *Bot) SetMyDescription(ctx context.Context, opts ...SetMyDescriptionOpts) (bool, error) {
	req := &SetMyDescriptionRequest{}
	if len(opts) > 0 {
		req.SetMyDescriptionOpts = opts[0]
	}
	return Call[bool](ctx, b.BotClient, "setMyDescription", req)
}

// GetMyDescription calls the "getMyDescription" Bot API method.
func (b *Bot) GetMyDescription(ctx context.Context, opts ...GetMyDescriptionOpts) (*BotDescription, error) {
	req := &GetMyDescriptionRequest{}
	if len(opts) > 0 {
		req.GetMyDescriptionOpts = opts[0]
	}
	return Call[*BotDescription](ctx, b.BotClient, "getMyDescription", req)
}

// SetMyShortDescription calls the "setMyShortDescription" Bot API method.
func (b *Bot) SetMyShortDescription(ctx context.Context, opts ...SetMyShortDescriptionOpts) (bool, error) {
	req := &SetMyShortDescriptionRequest{}
	if len(opts) > 0 {
		req.SetMyShortDescriptionOpts = opts[0]
	}
	return Call[bool](ctx, b.BotClient, "setMyShortDescription", req)
}

// GetMyShortDescription calls the "getMyShortDescription" Bot API method.
func (b *Bot) GetMyShortDescription(ctx context.Context, opts ...GetMyShortDescriptionOpts) (*BotShortDescription, error) {
	req := &GetMyShortDescriptionRequest{}
	if len(opts) > 0 {
		req.GetMyShortDescriptionOpts = opts[0]
	}
	return Call[*BotShortDescription](ctx, b.BotClient, "getMyShortDescription", req)
}

// SetMyProfilePhoto calls the "setMyProfilePhoto" Bot API method.
func (b *Bot) SetMyProfilePhoto(ctx context.Context, photo InputProfilePhoto) (bool, error) {
	return Call[bool](ctx, b.BotClient, "setMyProfilePhoto", &SetMyProfilePhotoRequest{Photo: photo})
}

// RemoveMyProfilePhoto calls the "removeMyProfilePhoto" Bot API method.
func (b *Bot) RemoveMyProfilePhoto(ctx context.Context) (bool, error) {
	return Call[bool](ctx, b.BotClient, "removeMyProfilePhoto", &RemoveMyProfilePhotoRequest{})
}

// SetChatMenuButton calls the "setChatMenuButton" Bot API method.
func (b *Bot) SetChatMenuButton(ctx context.Context, opts ...SetChatMenuButtonOpts) (bool, error) {
	req := &SetChatMenuButtonRequest{}
	if len(opts) > 0 {
		req.SetChatMenuButtonOpts = opts[0]
	}
	return Call[bool](ctx, b.BotClient, "setChatMenuButton", req)
}

// GetChatMenuButton calls the "getChatMenuButton" Bot API method.
func (b *Bot) GetChatMenuButton(ctx context.Context, opts ...GetChatMenuButtonOpts) (MenuButton, error) {
	req := &GetChatMenuButtonRequest{}
	if len(opts) > 0 {
		req.GetChatMenuButtonOpts = opts[0]
	}
	raw, err := b.BotClient.RequestWithContext(ctx, "getChatMenuButton", req)
	if err != nil {
		return nil, err
	}
	return DecodeMenuButton(raw)
}

// SetMyDefaultAdministratorRights calls the "setMyDefaultAdministratorRights" Bot API method.
func (b *Bot) SetMyDefaultAdministratorRights(ctx context.Context, opts ...SetMyDefaultAdministratorRightsOpts) (bool, error) {
	req := &SetMyDefaultAdministratorRightsRequest{}
	if len(opts) > 0 {
		req.SetMyDefaultAdministratorRightsOpts = opts[0]
	}
	return Call[bool](ctx, b.BotClient, "setMyDefaultAdministratorRights", req)
}

// GetMyDefaultAdministratorRights calls the "getMyDefaultAdministratorRights" Bot API method.
func (b *Bot) GetMyDefaultAdministratorRights(ctx context.Context, opts ...GetMyDefaultAdministratorRightsOpts) (*ChatAdministratorRights, error) {
	req := &GetMyDefaultAdministratorRightsRequest{}
	if len(opts) > 0 {
		req.GetMyDefaultAdministratorRightsOpts = opts[0]
	}
	return Call[*ChatAdministratorRights](ctx, b.BotClient, "getMyDefaultAdministratorRights", req)
}

// GetAvailableGifts calls the "getAvailableGifts" Bot API method.
func (b *Bot) GetAvailableGifts(ctx context.Context) (*Gifts, error) {
	return Call[*Gifts](ctx, b.BotClient, "getAvailableGifts", &GetAvailableGiftsRequest{})
}

// SendGift calls the "sendGift" Bot API method.
func (b *Bot) SendGift(ctx context.Context, giftID string, opts ...SendGiftOpts) (bool, error) {
	req := &SendGiftRequest{GiftID: giftID}
	if len(opts) > 0 {
		req.SendGiftOpts = opts[0]
	}
	return Call[bool](ctx, b.BotClient, "sendGift", req)
}

// GiftPremiumSubscription calls the "giftPremiumSubscription" Bot API method.
func (b *Bot) GiftPremiumSubscription(ctx context.Context, userID int64, monthCount int64, starCount int64, opts ...GiftPremiumSubscriptionOpts) (bool, error) {
	req := &GiftPremiumSubscriptionRequest{UserID: userID, MonthCount: monthCount, StarCount: starCount}
	if len(opts) > 0 {
		req.GiftPremiumSubscriptionOpts = opts[0]
	}
	return Call[bool](ctx, b.BotClient, "giftPremiumSubscription", req)
}

// VerifyUser calls the "verifyUser" Bot API method.
func (b *Bot) VerifyUser(ctx context.Context, userID int64, opts ...VerifyUserOpts) (bool, error) {
	req := &VerifyUserRequest{UserID: userID}
	if len(opts) > 0 {
		req.VerifyUserOpts = opts[0]
	}
	return Call[bool](ctx, b.BotClient, "verifyUser", req)
}

// VerifyChat calls the "verifyChat" Bot API method.
func (b *Bot) VerifyChat(ctx context.Context, chatID int64, opts ...VerifyChatOpts) (bool, error) {
	req := &VerifyChatRequest{ChatID: chatID}
	if len(opts) > 0 {
		req.VerifyChatOpts = opts[0]
	}
	return Call[bool](ctx, b.BotClient, "verifyChat", req)
}

// RemoveUserVerification calls the "removeUserVerification" Bot API method.
func (b *Bot) RemoveUserVerification(ctx context.Context, userID int64) (bool, error) {
	return Call[bool](ctx, b.BotClient, "removeUserVerification", &RemoveUserVerificationRequest{UserID: userID})
}

// RemoveChatVerification calls the "removeChatVerification" Bot API method.
func (b *Bot) RemoveChatVerification(ctx context.Context, chatID int64) (bool, error) {
	return Call[bool](ctx, b.BotClient, "removeChatVerification", &RemoveChatVerificationRequest{ChatID: chatID})
}

// ReadBusinessMessage calls the "readBusinessMessage" Bot API method.
func (b *Bot) ReadBusinessMessage(ctx context.Context, businessConnectionID string, chatID int64, messageID int64) (bool, error) {
	return Call[bool](ctx, b.BotClient, "readBusinessMessage", &ReadBusinessMessageRequest{BusinessConnectionID: businessConnectionID, ChatID: chatID, MessageID: messageID})
}

// DeleteBusinessMessages calls the "deleteBusinessMessages" Bot API method.
func (b *Bot) DeleteBusinessMessages(ctx context.Context, businessConnectionID string, messageIDs []int64) (bool, error) {
	return Call[bool](ctx, b.BotClient, "deleteBusinessMessages", &DeleteBusinessMessagesRequest{BusinessConnectionID: businessConnectionID, MessageIDs: messageIDs})
}

// SetBusinessAccountName calls the "setBusinessAccountName" Bot API method.
func (b *Bot) SetBusinessAccountName(ctx context.Context, businessConnectionID string, firstName string, opts ...SetBusinessAccountNameOpts) (bool, error) {
	req := &SetBusinessAccountNameRequest{BusinessConnectionID: businessConnectionID, FirstName: firstName}
	if len(opts) > 0 {
		req.SetBusinessAccountNameOpts = opts[0]
	}
	return Call[bool](ctx, b.BotClient, "setBusinessAccountName", req)
}

// SetBusinessAccountUsername calls the "setBusinessAccountUsername" Bot API method.
func (b *Bot) SetBusinessAccountUsername(ctx context.Context, businessConnectionID string, opts ...SetBusinessAccountUsernameOpts) (bool, error) {
	req := &SetBusinessAccountUsernameRequest{BusinessConnectionID: businessConnectionID}
	if len(opts) > 0 {
		req.SetBusinessAccountUsernameOpts = opts[0]
	}
	return Call[bool](ctx, b.BotClient, "setBusinessAccountUsername", req)
}

// SetBusinessAccountBio calls the "setBusinessAccountBio" Bot API method.
func (b *Bot) SetBusinessAccountBio(ctx context.Context, businessConnectionID string, opts ...SetBusinessAccountBioOpts) (bool, error) {
	req := &SetBusinessAccountBioRequest{BusinessConnectionID: businessConnectionID}
	if len(opts) > 0 {
		req.SetBusinessAccountBioOpts = opts[0]
	}
	return Call[bool](ctx, b.BotClient, "setBusinessAccountBio", req)
}

// SetBusinessAccountProfilePhoto calls the "setBusinessAccountProfilePhoto" Bot API method.
func (b *Bot) SetBusinessAccountProfilePhoto(ctx context.Context, businessConnectionID string, photo InputProfilePhoto, opts ...SetBusinessAccountProfilePhotoOpts) (bool, error) {
	req := &SetBusinessAccountProfilePhotoRequest{BusinessConnectionID: businessConnectionID, Photo: photo}
	if len(opts) > 0 {
		req.SetBusinessAccountProfilePhotoOpts = opts[0]
	}
	return Call[bool](ctx, b.BotClient, "setBusinessAccountProfilePhoto", req)
}

// RemoveBusinessAccountProfilePhoto calls the "removeBusinessAccountProfilePhoto" Bot API method.
func (b *Bot) RemoveBusinessAccountProfilePhoto(ctx context.Context, businessConnectionID string, opts ...RemoveBusinessAccountProfilePhotoOpts) (bool, error) {
	req := &RemoveBusinessAccountProfilePhotoRequest{BusinessConnectionID: businessConnectionID}
	if len(opts) > 0 {
		req.RemoveBusinessAccountProfilePhotoOpts = opts[0]
	}
	return Call[bool](ctx, b.BotClient, "removeBusinessAccountProfilePhoto", req)
}

// SetBusinessAccountGiftSettings calls the "setBusinessAccountGiftSettings" Bot API method.
func (b *Bot) SetBusinessAccountGiftSettings(ctx context.Context, businessConnectionID string, showGiftButton bool, acceptedGiftTypes *AcceptedGiftTypes) (bool, error) {
	return Call[bool](ctx, b.BotClient, "setBusinessAccountGiftSettings", &SetBusinessAccountGiftSettingsRequest{BusinessConnectionID: businessConnectionID, ShowGiftButton: showGiftButton, AcceptedGiftTypes: acceptedGiftTypes})
}

// GetBusinessAccountStarBalance calls the "getBusinessAccountStarBalance" Bot API method.
func (b *Bot) GetBusinessAccountStarBalance(ctx context.Context, businessConnectionID string) (*StarAmount, error) {
	return Call[*StarAmount](ctx, b.BotClient, "getBusinessAccountStarBalance", &GetBusinessAccountStarBalanceRequest{BusinessConnectionID: businessConnectionID})
}

// TransferBusinessAccountStars calls the "transferBusinessAccountStars" Bot API method.
func (b *Bot) TransferBusinessAccountStars(ctx context.Context, businessConnectionID string, starCount int64) (bool, error) {
	return Call[bool](ctx, b.BotClient, "transferBusinessAccountStars", &TransferBusinessAccountStarsRequest{BusinessConnectionID: businessConnectionID, StarCount: starCount})
}

// GetBusinessAccountGifts calls the "getBusinessAccountGifts" Bot API method.
func (b *Bot) GetBusinessAccountGifts(ctx context.Context, businessConnectionID string, opts ...GetBusinessAccountGiftsOpts) (*OwnedGifts, error) {
	req := &GetBusinessAccountGiftsRequest{BusinessConnectionID: businessConnectionID}
	if len(opts) > 0 {
		req.GetBusinessAccountGiftsOpts = opts[0]
	}
	return Call[*OwnedGifts](ctx, b.BotClient, "getBusinessAccountGifts", req)
}

// GetUserGifts calls the "getUserGifts" Bot API method.
func (b *Bot) GetUserGifts(ctx context.Context, userID int64, opts ...GetUserGiftsOpts) (*OwnedGifts, error) {
	req := &GetUserGiftsRequest{UserID: userID}
	if len(opts) > 0 {
		req.GetUserGiftsOpts = opts[0]
	}
	return Call[*OwnedGifts](ctx, b.BotClient, "getUserGifts", req)
}

// GetChatGifts calls the "getChatGifts" Bot API method.
func (b *Bot) GetChatGifts(ctx context.Context, chatID int64, opts ...GetChatGiftsOpts) (*OwnedGifts, error) {
	req := &GetChatGiftsRequest{ChatID: chatID}
	if len(opts) > 0 {
		req.GetChatGiftsOpts = opts[0]
	}
	return Call[*OwnedGifts](ctx, b.BotClient, "getChatGifts", req)
}

// ConvertGiftToStars calls the "convertGiftToStars" Bot API method.
func (b *Bot) ConvertGiftToStars(ctx context.Context, businessConnectionID string, ownedGiftID string) (bool, error) {
	return Call[bool](ctx, b.BotClient, "convertGiftToStars", &ConvertGiftToStarsRequest{BusinessConnectionID: businessConnectionID, OwnedGiftID: ownedGiftID})
}

// UpgradeGift calls the "upgradeGift" Bot API method.
func (b *Bot) UpgradeGift(ctx context.Context, businessConnectionID string, ownedGiftID string, opts ...UpgradeGiftOpts) (bool, error) {
	req := &UpgradeGiftRequest{BusinessConnectionID: businessConnectionID, OwnedGiftID: ownedGiftID}
	if len(opts) > 0 {
		req.UpgradeGiftOpts = opts[0]
	}
	return Call[bool](ctx, b.BotClient, "upgradeGift", req)
}

// TransferGift calls the "transferGift" Bot API method.
func (b *Bot) TransferGift(ctx context.Context, businessConnectionID string, ownedGiftID string, newOwnerChatID int64, opts ...TransferGiftOpts) (bool, error) {
	req := &TransferGiftRequest{BusinessConnectionID: businessConnectionID, OwnedGiftID: ownedGiftID, NewOwnerChatID: newOwnerChatID}
	if len(opts) > 0 {
		req.TransferGiftOpts = opts[0]
	}
	return Call[bool](ctx, b.BotClient, "transferGift", req)
}

// PostStory calls the "postStory" Bot API method.
func (b *Bot) PostStory(ctx context.Context, businessConnectionID string, content InputStoryContent, activePeriod int64, opts ...PostStoryOpts) (*Story, error) {
	req := &PostStoryRequest{BusinessConnectionID: businessConnectionID, Content: content, ActivePeriod: activePeriod}
	if len(opts) > 0 {
		req.PostStoryOpts = opts[0]
	}
	return Call[*Story](ctx, b.BotClient, "postStory", req)
}

// RepostStory calls the "repostStory" Bot API method.
func (b *Bot) RepostStory(ctx context.Context, businessConnectionID string, fromChatID int64, fromStoryID int64, activePeriod int64, opts ...RepostStoryOpts) (*Story, error) {
	req := &RepostStoryRequest{BusinessConnectionID: businessConnectionID, FromChatID: fromChatID, FromStoryID: fromStoryID, ActivePeriod: activePeriod}
	if len(opts) > 0 {
		req.RepostStoryOpts = opts[0]
	}
	return Call[*Story](ctx, b.BotClient, "repostStory", req)
}

// EditStory calls the "editStory" Bot API method.
func (b *Bot) EditStory(ctx context.Context, businessConnectionID string, storyID int64, content InputStoryContent, opts ...EditStoryOpts) (*Story, error) {
	req := &EditStoryRequest{BusinessConnectionID: businessConnectionID, StoryID: storyID, Content: content}
	if len(opts) > 0 {
		req.EditStoryOpts = opts[0]
	}
	return Call[*Story](ctx, b.BotClient, "editStory", req)
}

// DeleteStory calls the "deleteStory" Bot API method.
func (b *Bot) DeleteStory(ctx context.Context, businessConnectionID string, storyID int64) (bool, error) {
	return Call[bool](ctx, b.BotClient, "deleteStory", &DeleteStoryRequest{BusinessConnectionID: businessConnectionID, StoryID: storyID})
}

// AnswerWebAppQuery calls the "answerWebAppQuery" Bot API method.
func (b *Bot) AnswerWebAppQuery(ctx context.Context, webAppQueryID string, result InlineQueryResult) (*SentWebAppMessage, error) {
	return Call[*SentWebAppMessage](ctx, b.BotClient, "answerWebAppQuery", &AnswerWebAppQueryRequest{WebAppQueryID: webAppQueryID, Result: result})
}

// SavePreparedInlineMessage calls the "savePreparedInlineMessage" Bot API method.
func (b *Bot) SavePreparedInlineMessage(ctx context.Context, userID int64, result InlineQueryResult, opts ...SavePreparedInlineMessageOpts) (*PreparedInlineMessage, error) {
	req := &SavePreparedInlineMessageRequest{UserID: userID, Result: result}
	if len(opts) > 0 {
		req.SavePreparedInlineMessageOpts = opts[0]
	}
	return Call[*PreparedInlineMessage](ctx, b.BotClient, "savePreparedInlineMessage", req)
}

// SavePreparedKeyboardButton calls the "savePreparedKeyboardButton" Bot API method.
func (b *Bot) SavePreparedKeyboardButton(ctx context.Context, userID int64, button *KeyboardButton) (*PreparedKeyboardButton, error) {
	return Call[*PreparedKeyboardButton](ctx, b.BotClient, "savePreparedKeyboardButton", &SavePreparedKeyboardButtonRequest{UserID: userID, Button: button})
}

// EditMessageText calls the "editMessageText" Bot API method.
func (b *Bot) EditMessageText(ctx context.Context, opts ...EditMessageTextOpts) (*Message, bool, error) {
	req := &EditMessageTextRequest{}
	if len(opts) > 0 {
		req.EditMessageTextOpts = opts[0]
	}
	raw, err := b.BotClient.RequestWithContext(ctx, "editMessageText", req)
	if err != nil {
		return nil, false, err
	}
	var msg Message
	if err := json.Unmarshal(raw, &msg); err != nil {
		var ok bool
		if err := json.Unmarshal(raw, &ok); err != nil {
			return nil, false, err
		}
		return nil, ok, nil
	}
	return &msg, true, nil
}

// EditMessageCaption calls the "editMessageCaption" Bot API method.
func (b *Bot) EditMessageCaption(ctx context.Context, opts ...EditMessageCaptionOpts) (*Message, bool, error) {
	req := &EditMessageCaptionRequest{}
	if len(opts) > 0 {
		req.EditMessageCaptionOpts = opts[0]
	}
	raw, err := b.BotClient.RequestWithContext(ctx, "editMessageCaption", req)
	if err != nil {
		return nil, false, err
	}
	var msg Message
	if err := json.Unmarshal(raw, &msg); err != nil {
		var ok bool
		if err := json.Unmarshal(raw, &ok); err != nil {
			return nil, false, err
		}
		return nil, ok, nil
	}
	return &msg, true, nil
}

// EditMessageMedia calls the "editMessageMedia" Bot API method.
func (b *Bot) EditMessageMedia(ctx context.Context, media InputMedia, opts ...EditMessageMediaOpts) (*Message, bool, error) {
	req := &EditMessageMediaRequest{Media: media}
	if len(opts) > 0 {
		req.EditMessageMediaOpts = opts[0]
	}
	raw, err := b.BotClient.RequestWithContext(ctx, "editMessageMedia", req)
	if err != nil {
		return nil, false, err
	}
	var msg Message
	if err := json.Unmarshal(raw, &msg); err != nil {
		var ok bool
		if err := json.Unmarshal(raw, &ok); err != nil {
			return nil, false, err
		}
		return nil, ok, nil
	}
	return &msg, true, nil
}

// EditMessageLiveLocation calls the "editMessageLiveLocation" Bot API method.
func (b *Bot) EditMessageLiveLocation(ctx context.Context, latitude float64, longitude float64, opts ...EditMessageLiveLocationOpts) (*Message, bool, error) {
	req := &EditMessageLiveLocationRequest{Latitude: latitude, Longitude: longitude}
	if len(opts) > 0 {
		req.EditMessageLiveLocationOpts = opts[0]
	}
	raw, err := b.BotClient.RequestWithContext(ctx, "editMessageLiveLocation", req)
	if err != nil {
		return nil, false, err
	}
	var msg Message
	if err := json.Unmarshal(raw, &msg); err != nil {
		var ok bool
		if err := json.Unmarshal(raw, &ok); err != nil {
			return nil, false, err
		}
		return nil, ok, nil
	}
	return &msg, true, nil
}

// StopMessageLiveLocation calls the "stopMessageLiveLocation" Bot API method.
func (b *Bot) StopMessageLiveLocation(ctx context.Context, opts ...StopMessageLiveLocationOpts) (*Message, bool, error) {
	req := &StopMessageLiveLocationRequest{}
	if len(opts) > 0 {
		req.StopMessageLiveLocationOpts = opts[0]
	}
	raw, err := b.BotClient.RequestWithContext(ctx, "stopMessageLiveLocation", req)
	if err != nil {
		return nil, false, err
	}
	var msg Message
	if err := json.Unmarshal(raw, &msg); err != nil {
		var ok bool
		if err := json.Unmarshal(raw, &ok); err != nil {
			return nil, false, err
		}
		return nil, ok, nil
	}
	return &msg, true, nil
}

// EditMessageChecklist calls the "editMessageChecklist" Bot API method.
func (b *Bot) EditMessageChecklist(ctx context.Context, businessConnectionID string, chatID int64, messageID int64, checklist *InputChecklist, opts ...EditMessageChecklistOpts) (*Message, error) {
	req := &EditMessageChecklistRequest{BusinessConnectionID: businessConnectionID, ChatID: chatID, MessageID: messageID, Checklist: checklist}
	if len(opts) > 0 {
		req.EditMessageChecklistOpts = opts[0]
	}
	return Call[*Message](ctx, b.BotClient, "editMessageChecklist", req)
}

// EditMessageReplyMarkup calls the "editMessageReplyMarkup" Bot API method.
func (b *Bot) EditMessageReplyMarkup(ctx context.Context, opts ...EditMessageReplyMarkupOpts) (*Message, bool, error) {
	req := &EditMessageReplyMarkupRequest{}
	if len(opts) > 0 {
		req.EditMessageReplyMarkupOpts = opts[0]
	}
	raw, err := b.BotClient.RequestWithContext(ctx, "editMessageReplyMarkup", req)
	if err != nil {
		return nil, false, err
	}
	var msg Message
	if err := json.Unmarshal(raw, &msg); err != nil {
		var ok bool
		if err := json.Unmarshal(raw, &ok); err != nil {
			return nil, false, err
		}
		return nil, ok, nil
	}
	return &msg, true, nil
}

// StopPoll calls the "stopPoll" Bot API method.
func (b *Bot) StopPoll(ctx context.Context, chatID int64, messageID int64, opts ...StopPollOpts) (*Poll, error) {
	req := &StopPollRequest{ChatID: chatID, MessageID: messageID}
	if len(opts) > 0 {
		req.StopPollOpts = opts[0]
	}
	return Call[*Poll](ctx, b.BotClient, "stopPoll", req)
}

// EditEphemeralMessageText calls the "editEphemeralMessageText" Bot API method.
func (b *Bot) EditEphemeralMessageText(ctx context.Context, chatID int64, receiverUserID int64, ephemeralMessageID int64, opts ...EditEphemeralMessageTextOpts) (bool, error) {
	req := &EditEphemeralMessageTextRequest{ChatID: chatID, ReceiverUserID: receiverUserID, EphemeralMessageID: ephemeralMessageID}
	if len(opts) > 0 {
		req.EditEphemeralMessageTextOpts = opts[0]
	}
	return Call[bool](ctx, b.BotClient, "editEphemeralMessageText", req)
}

// EditEphemeralMessageMedia calls the "editEphemeralMessageMedia" Bot API method.
func (b *Bot) EditEphemeralMessageMedia(ctx context.Context, chatID int64, receiverUserID int64, ephemeralMessageID int64, media InputMedia, opts ...EditEphemeralMessageMediaOpts) (bool, error) {
	req := &EditEphemeralMessageMediaRequest{ChatID: chatID, ReceiverUserID: receiverUserID, EphemeralMessageID: ephemeralMessageID, Media: media}
	if len(opts) > 0 {
		req.EditEphemeralMessageMediaOpts = opts[0]
	}
	return Call[bool](ctx, b.BotClient, "editEphemeralMessageMedia", req)
}

// EditEphemeralMessageCaption calls the "editEphemeralMessageCaption" Bot API method.
func (b *Bot) EditEphemeralMessageCaption(ctx context.Context, chatID int64, receiverUserID int64, ephemeralMessageID int64, opts ...EditEphemeralMessageCaptionOpts) (bool, error) {
	req := &EditEphemeralMessageCaptionRequest{ChatID: chatID, ReceiverUserID: receiverUserID, EphemeralMessageID: ephemeralMessageID}
	if len(opts) > 0 {
		req.EditEphemeralMessageCaptionOpts = opts[0]
	}
	return Call[bool](ctx, b.BotClient, "editEphemeralMessageCaption", req)
}

// EditEphemeralMessageReplyMarkup calls the "editEphemeralMessageReplyMarkup" Bot API method.
func (b *Bot) EditEphemeralMessageReplyMarkup(ctx context.Context, chatID int64, receiverUserID int64, ephemeralMessageID int64, opts ...EditEphemeralMessageReplyMarkupOpts) (bool, error) {
	req := &EditEphemeralMessageReplyMarkupRequest{ChatID: chatID, ReceiverUserID: receiverUserID, EphemeralMessageID: ephemeralMessageID}
	if len(opts) > 0 {
		req.EditEphemeralMessageReplyMarkupOpts = opts[0]
	}
	return Call[bool](ctx, b.BotClient, "editEphemeralMessageReplyMarkup", req)
}

// ApproveSuggestedPost calls the "approveSuggestedPost" Bot API method.
func (b *Bot) ApproveSuggestedPost(ctx context.Context, chatID int64, messageID int64, opts ...ApproveSuggestedPostOpts) (bool, error) {
	req := &ApproveSuggestedPostRequest{ChatID: chatID, MessageID: messageID}
	if len(opts) > 0 {
		req.ApproveSuggestedPostOpts = opts[0]
	}
	return Call[bool](ctx, b.BotClient, "approveSuggestedPost", req)
}

// DeclineSuggestedPost calls the "declineSuggestedPost" Bot API method.
func (b *Bot) DeclineSuggestedPost(ctx context.Context, chatID int64, messageID int64, opts ...DeclineSuggestedPostOpts) (bool, error) {
	req := &DeclineSuggestedPostRequest{ChatID: chatID, MessageID: messageID}
	if len(opts) > 0 {
		req.DeclineSuggestedPostOpts = opts[0]
	}
	return Call[bool](ctx, b.BotClient, "declineSuggestedPost", req)
}

// DeleteMessage calls the "deleteMessage" Bot API method.
func (b *Bot) DeleteMessage(ctx context.Context, chatID int64, messageID int64) (bool, error) {
	return Call[bool](ctx, b.BotClient, "deleteMessage", &DeleteMessageRequest{ChatID: chatID, MessageID: messageID})
}

// DeleteMessages calls the "deleteMessages" Bot API method.
func (b *Bot) DeleteMessages(ctx context.Context, chatID int64, messageIDs []int64) (bool, error) {
	return Call[bool](ctx, b.BotClient, "deleteMessages", &DeleteMessagesRequest{ChatID: chatID, MessageIDs: messageIDs})
}

// DeleteEphemeralMessage calls the "deleteEphemeralMessage" Bot API method.
func (b *Bot) DeleteEphemeralMessage(ctx context.Context, chatID int64, receiverUserID int64, ephemeralMessageID int64) (bool, error) {
	return Call[bool](ctx, b.BotClient, "deleteEphemeralMessage", &DeleteEphemeralMessageRequest{ChatID: chatID, ReceiverUserID: receiverUserID, EphemeralMessageID: ephemeralMessageID})
}

// DeleteMessageReaction calls the "deleteMessageReaction" Bot API method.
func (b *Bot) DeleteMessageReaction(ctx context.Context, chatID int64, messageID int64, opts ...DeleteMessageReactionOpts) (bool, error) {
	req := &DeleteMessageReactionRequest{ChatID: chatID, MessageID: messageID}
	if len(opts) > 0 {
		req.DeleteMessageReactionOpts = opts[0]
	}
	return Call[bool](ctx, b.BotClient, "deleteMessageReaction", req)
}

// DeleteAllMessageReactions calls the "deleteAllMessageReactions" Bot API method.
func (b *Bot) DeleteAllMessageReactions(ctx context.Context, chatID int64, opts ...DeleteAllMessageReactionsOpts) (bool, error) {
	req := &DeleteAllMessageReactionsRequest{ChatID: chatID}
	if len(opts) > 0 {
		req.DeleteAllMessageReactionsOpts = opts[0]
	}
	return Call[bool](ctx, b.BotClient, "deleteAllMessageReactions", req)
}

// SendSticker calls the "sendSticker" Bot API method.
func (b *Bot) SendSticker(ctx context.Context, chatID int64, sticker *InputFile, opts ...SendStickerOpts) (*Message, error) {
	req := &SendStickerRequest{ChatID: chatID, Sticker: sticker}
	if len(opts) > 0 {
		req.SendStickerOpts = opts[0]
	}
	return Call[*Message](ctx, b.BotClient, "sendSticker", req)
}

// GetStickerSet calls the "getStickerSet" Bot API method.
func (b *Bot) GetStickerSet(ctx context.Context, name string) (*StickerSet, error) {
	return Call[*StickerSet](ctx, b.BotClient, "getStickerSet", &GetStickerSetRequest{Name: name})
}

// GetCustomEmojiStickers calls the "getCustomEmojiStickers" Bot API method.
func (b *Bot) GetCustomEmojiStickers(ctx context.Context, customEmojiIDs []string) ([]Sticker, error) {
	return Call[[]Sticker](ctx, b.BotClient, "getCustomEmojiStickers", &GetCustomEmojiStickersRequest{CustomEmojiIDs: customEmojiIDs})
}

// UploadStickerFile calls the "uploadStickerFile" Bot API method.
func (b *Bot) UploadStickerFile(ctx context.Context, userID int64, sticker *InputFile, stickerFormat UploadStickerFileStickerFormat) (*File, error) {
	return Call[*File](ctx, b.BotClient, "uploadStickerFile", &UploadStickerFileRequest{UserID: userID, Sticker: sticker, StickerFormat: stickerFormat})
}

// CreateNewStickerSet calls the "createNewStickerSet" Bot API method.
func (b *Bot) CreateNewStickerSet(ctx context.Context, userID int64, name string, title string, stickers []InputSticker, opts ...CreateNewStickerSetOpts) (bool, error) {
	req := &CreateNewStickerSetRequest{UserID: userID, Name: name, Title: title, Stickers: stickers}
	if len(opts) > 0 {
		req.CreateNewStickerSetOpts = opts[0]
	}
	return Call[bool](ctx, b.BotClient, "createNewStickerSet", req)
}

// AddStickerToSet calls the "addStickerToSet" Bot API method.
func (b *Bot) AddStickerToSet(ctx context.Context, userID int64, name string, sticker *InputSticker) (bool, error) {
	return Call[bool](ctx, b.BotClient, "addStickerToSet", &AddStickerToSetRequest{UserID: userID, Name: name, Sticker: sticker})
}

// SetStickerPositionInSet calls the "setStickerPositionInSet" Bot API method.
func (b *Bot) SetStickerPositionInSet(ctx context.Context, sticker string, position int64) (bool, error) {
	return Call[bool](ctx, b.BotClient, "setStickerPositionInSet", &SetStickerPositionInSetRequest{Sticker: sticker, Position: position})
}

// DeleteStickerFromSet calls the "deleteStickerFromSet" Bot API method.
func (b *Bot) DeleteStickerFromSet(ctx context.Context, sticker string) (bool, error) {
	return Call[bool](ctx, b.BotClient, "deleteStickerFromSet", &DeleteStickerFromSetRequest{Sticker: sticker})
}

// ReplaceStickerInSet calls the "replaceStickerInSet" Bot API method.
func (b *Bot) ReplaceStickerInSet(ctx context.Context, userID int64, name string, oldSticker string, sticker *InputSticker) (bool, error) {
	return Call[bool](ctx, b.BotClient, "replaceStickerInSet", &ReplaceStickerInSetRequest{UserID: userID, Name: name, OldSticker: oldSticker, Sticker: sticker})
}

// SetStickerEmojiList calls the "setStickerEmojiList" Bot API method.
func (b *Bot) SetStickerEmojiList(ctx context.Context, sticker string, emojiList []string) (bool, error) {
	return Call[bool](ctx, b.BotClient, "setStickerEmojiList", &SetStickerEmojiListRequest{Sticker: sticker, EmojiList: emojiList})
}

// SetStickerKeywords calls the "setStickerKeywords" Bot API method.
func (b *Bot) SetStickerKeywords(ctx context.Context, sticker string, opts ...SetStickerKeywordsOpts) (bool, error) {
	req := &SetStickerKeywordsRequest{Sticker: sticker}
	if len(opts) > 0 {
		req.SetStickerKeywordsOpts = opts[0]
	}
	return Call[bool](ctx, b.BotClient, "setStickerKeywords", req)
}

// SetStickerMaskPosition calls the "setStickerMaskPosition" Bot API method.
func (b *Bot) SetStickerMaskPosition(ctx context.Context, sticker string, opts ...SetStickerMaskPositionOpts) (bool, error) {
	req := &SetStickerMaskPositionRequest{Sticker: sticker}
	if len(opts) > 0 {
		req.SetStickerMaskPositionOpts = opts[0]
	}
	return Call[bool](ctx, b.BotClient, "setStickerMaskPosition", req)
}

// SetStickerSetTitle calls the "setStickerSetTitle" Bot API method.
func (b *Bot) SetStickerSetTitle(ctx context.Context, name string, title string) (bool, error) {
	return Call[bool](ctx, b.BotClient, "setStickerSetTitle", &SetStickerSetTitleRequest{Name: name, Title: title})
}

// SetStickerSetThumbnail calls the "setStickerSetThumbnail" Bot API method.
func (b *Bot) SetStickerSetThumbnail(ctx context.Context, name string, userID int64, format SetStickerSetThumbnailFormat, opts ...SetStickerSetThumbnailOpts) (bool, error) {
	req := &SetStickerSetThumbnailRequest{Name: name, UserID: userID, Format: format}
	if len(opts) > 0 {
		req.SetStickerSetThumbnailOpts = opts[0]
	}
	return Call[bool](ctx, b.BotClient, "setStickerSetThumbnail", req)
}

// SetCustomEmojiStickerSetThumbnail calls the "setCustomEmojiStickerSetThumbnail" Bot API method.
func (b *Bot) SetCustomEmojiStickerSetThumbnail(ctx context.Context, name string, opts ...SetCustomEmojiStickerSetThumbnailOpts) (bool, error) {
	req := &SetCustomEmojiStickerSetThumbnailRequest{Name: name}
	if len(opts) > 0 {
		req.SetCustomEmojiStickerSetThumbnailOpts = opts[0]
	}
	return Call[bool](ctx, b.BotClient, "setCustomEmojiStickerSetThumbnail", req)
}

// DeleteStickerSet calls the "deleteStickerSet" Bot API method.
func (b *Bot) DeleteStickerSet(ctx context.Context, name string) (bool, error) {
	return Call[bool](ctx, b.BotClient, "deleteStickerSet", &DeleteStickerSetRequest{Name: name})
}

// SendRichMessage calls the "sendRichMessage" Bot API method.
func (b *Bot) SendRichMessage(ctx context.Context, chatID int64, richMessage *InputRichMessage, opts ...SendRichMessageOpts) (*Message, error) {
	req := &SendRichMessageRequest{ChatID: chatID, RichMessage: richMessage}
	if len(opts) > 0 {
		req.SendRichMessageOpts = opts[0]
	}
	return Call[*Message](ctx, b.BotClient, "sendRichMessage", req)
}

// SendRichMessageDraft calls the "sendRichMessageDraft" Bot API method.
func (b *Bot) SendRichMessageDraft(ctx context.Context, chatID int64, draftID int64, richMessage *InputRichMessage, opts ...SendRichMessageDraftOpts) (bool, error) {
	req := &SendRichMessageDraftRequest{ChatID: chatID, DraftID: draftID, RichMessage: richMessage}
	if len(opts) > 0 {
		req.SendRichMessageDraftOpts = opts[0]
	}
	return Call[bool](ctx, b.BotClient, "sendRichMessageDraft", req)
}

// AnswerInlineQuery calls the "answerInlineQuery" Bot API method.
func (b *Bot) AnswerInlineQuery(ctx context.Context, inlineQueryID string, results []InlineQueryResult, opts ...AnswerInlineQueryOpts) (bool, error) {
	req := &AnswerInlineQueryRequest{InlineQueryID: inlineQueryID, Results: results}
	if len(opts) > 0 {
		req.AnswerInlineQueryOpts = opts[0]
	}
	return Call[bool](ctx, b.BotClient, "answerInlineQuery", req)
}

// SendInvoice calls the "sendInvoice" Bot API method.
func (b *Bot) SendInvoice(ctx context.Context, chatID int64, title string, description string, payload string, currency string, prices []LabeledPrice, opts ...SendInvoiceOpts) (*Message, error) {
	req := &SendInvoiceRequest{ChatID: chatID, Title: title, Description: description, Payload: payload, Currency: currency, Prices: prices}
	if len(opts) > 0 {
		req.SendInvoiceOpts = opts[0]
	}
	return Call[*Message](ctx, b.BotClient, "sendInvoice", req)
}

// CreateInvoiceLink calls the "createInvoiceLink" Bot API method.
func (b *Bot) CreateInvoiceLink(ctx context.Context, title string, description string, payload string, currency string, prices []LabeledPrice, opts ...CreateInvoiceLinkOpts) (string, error) {
	req := &CreateInvoiceLinkRequest{Title: title, Description: description, Payload: payload, Currency: currency, Prices: prices}
	if len(opts) > 0 {
		req.CreateInvoiceLinkOpts = opts[0]
	}
	return Call[string](ctx, b.BotClient, "createInvoiceLink", req)
}

// AnswerShippingQuery calls the "answerShippingQuery" Bot API method.
func (b *Bot) AnswerShippingQuery(ctx context.Context, shippingQueryID string, ok bool, opts ...AnswerShippingQueryOpts) (bool, error) {
	req := &AnswerShippingQueryRequest{ShippingQueryID: shippingQueryID, Ok: ok}
	if len(opts) > 0 {
		req.AnswerShippingQueryOpts = opts[0]
	}
	return Call[bool](ctx, b.BotClient, "answerShippingQuery", req)
}

// AnswerPreCheckoutQuery calls the "answerPreCheckoutQuery" Bot API method.
func (b *Bot) AnswerPreCheckoutQuery(ctx context.Context, preCheckoutQueryID string, ok bool, opts ...AnswerPreCheckoutQueryOpts) (bool, error) {
	req := &AnswerPreCheckoutQueryRequest{PreCheckoutQueryID: preCheckoutQueryID, Ok: ok}
	if len(opts) > 0 {
		req.AnswerPreCheckoutQueryOpts = opts[0]
	}
	return Call[bool](ctx, b.BotClient, "answerPreCheckoutQuery", req)
}

// GetMyStarBalance calls the "getMyStarBalance" Bot API method.
func (b *Bot) GetMyStarBalance(ctx context.Context) (*StarAmount, error) {
	return Call[*StarAmount](ctx, b.BotClient, "getMyStarBalance", &GetMyStarBalanceRequest{})
}

// GetStarTransactions calls the "getStarTransactions" Bot API method.
func (b *Bot) GetStarTransactions(ctx context.Context, opts ...GetStarTransactionsOpts) (*StarTransactions, error) {
	req := &GetStarTransactionsRequest{}
	if len(opts) > 0 {
		req.GetStarTransactionsOpts = opts[0]
	}
	return Call[*StarTransactions](ctx, b.BotClient, "getStarTransactions", req)
}

// RefundStarPayment calls the "refundStarPayment" Bot API method.
func (b *Bot) RefundStarPayment(ctx context.Context, userID int64, telegramPaymentChargeID string) (bool, error) {
	return Call[bool](ctx, b.BotClient, "refundStarPayment", &RefundStarPaymentRequest{UserID: userID, TelegramPaymentChargeID: telegramPaymentChargeID})
}

// EditUserStarSubscription calls the "editUserStarSubscription" Bot API method.
func (b *Bot) EditUserStarSubscription(ctx context.Context, userID int64, telegramPaymentChargeID string, isCanceled bool) (bool, error) {
	return Call[bool](ctx, b.BotClient, "editUserStarSubscription", &EditUserStarSubscriptionRequest{UserID: userID, TelegramPaymentChargeID: telegramPaymentChargeID, IsCanceled: isCanceled})
}

// SetPassportDataErrors calls the "setPassportDataErrors" Bot API method.
func (b *Bot) SetPassportDataErrors(ctx context.Context, userID int64, errors []PassportElementError) (bool, error) {
	return Call[bool](ctx, b.BotClient, "setPassportDataErrors", &SetPassportDataErrorsRequest{UserID: userID, Errors: errors})
}

// SendGame calls the "sendGame" Bot API method.
func (b *Bot) SendGame(ctx context.Context, chatID int64, gameShortName string, opts ...SendGameOpts) (*Message, error) {
	req := &SendGameRequest{ChatID: chatID, GameShortName: gameShortName}
	if len(opts) > 0 {
		req.SendGameOpts = opts[0]
	}
	return Call[*Message](ctx, b.BotClient, "sendGame", req)
}

// SetGameScore calls the "setGameScore" Bot API method.
func (b *Bot) SetGameScore(ctx context.Context, userID int64, score int64, opts ...SetGameScoreOpts) (*Message, bool, error) {
	req := &SetGameScoreRequest{UserID: userID, Score: score}
	if len(opts) > 0 {
		req.SetGameScoreOpts = opts[0]
	}
	raw, err := b.BotClient.RequestWithContext(ctx, "setGameScore", req)
	if err != nil {
		return nil, false, err
	}
	var msg Message
	if err := json.Unmarshal(raw, &msg); err != nil {
		var ok bool
		if err := json.Unmarshal(raw, &ok); err != nil {
			return nil, false, err
		}
		return nil, ok, nil
	}
	return &msg, true, nil
}

// GetGameHighScores calls the "getGameHighScores" Bot API method.
func (b *Bot) GetGameHighScores(ctx context.Context, userID int64, opts ...GetGameHighScoresOpts) ([]GameHighScore, error) {
	req := &GetGameHighScoresRequest{UserID: userID}
	if len(opts) > 0 {
		req.GetGameHighScoresOpts = opts[0]
	}
	return Call[[]GameHighScore](ctx, b.BotClient, "getGameHighScores", req)
}
