// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	json "encoding/json"

	mock "github.com/stretchr/testify/mock"
)

// BotClient is an autogenerated mock type for the BotClient type
type BotClient struct {
	mock.Mock
}

// RequestWithContext provides a mock function with given fields: ctx, method, request
func (_m *BotClient) RequestWithContext(ctx context.Context, method string, request any) (json.RawMessage, error) {
	ret := _m.Called(ctx, method, request)

	if len(ret) == 0 {
		panic("no return value specified for RequestWithContext")
	}

	var r0 json.RawMessage
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, any) (json.RawMessage, error)); ok {
		return rf(ctx, method, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, any) json.RawMessage); ok {
		r0 = rf(ctx, method, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(json.RawMessage)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, any) error); ok {
		r1 = rf(ctx, method, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewBotClient creates a new instance of BotClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBotClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *BotClient {
	mock := &BotClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
