// Code generated by mockery v2.50.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Logger is an autogenerated mock type for the Logger type
type Logger struct {
	mock.Mock
}

// Debug provides a mock function with given fields: message, fields
func (_m *Logger) Debug(message string, fields map[string]interface{}) {
	_m.Called(message, fields)
}

// Error provides a mock function with given fields: err, message, fields
func (_m *Logger) Error(err error, message string, fields map[string]interface{}) {
	_m.Called(err, message, fields)
}

// Info provides a mock function with given fields: message, fields
func (_m *Logger) Info(message string, fields map[string]interface{}) {
	_m.Called(message, fields)
}

// Warn provides a mock function with given fields: message, fields
func (_m *Logger) Warn(message string, fields map[string]interface{}) {
	_m.Called(message, fields)
}

// NewLogger creates a new instance of Logger. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLogger(t interface {
	mock.TestingT
	Cleanup(func())
}) *Logger {
	mock := &Logger{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
